/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { activityActivityListAccountFeed } from "../funcs/activityActivityListAccountFeed.js";
import { activityActivityListGlobalFeed } from "../funcs/activityActivityListGlobalFeed.js";
import {
  activityActivityStreamGlobalFeed,
  ActivityStreamGlobalFeedAcceptEnum,
} from "../funcs/activityActivityStreamGlobalFeed.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export { ActivityStreamGlobalFeedAcceptEnum } from "../funcs/activityActivityStreamGlobalFeed.js";

export class Activity extends ClientSDK {
  /**
   * List the activity feed for a single account (profile timeline)
   */
  async activityListAccountFeed(
    request: components.V1ActivityListAccountFeedRequestBody,
    options?: RequestOptions,
  ): Promise<operations.ActivityListAccountFeedResponse> {
    return unwrapAsync(activityActivityListAccountFeed(
      this,
      request,
      options,
    ));
  }

  /**
   * List the global activity feed
   */
  async activityListGlobalFeed(
    request: components.V1ActivityListGlobalFeedRequestBody,
    options?: RequestOptions,
  ): Promise<operations.ActivityListGlobalFeedResponse> {
    return unwrapAsync(activityActivityListGlobalFeed(
      this,
      request,
      options,
    ));
  }

  /**
   * Live server-sent-events stream of the global activity feed
   */
  async activityStreamGlobalFeed(
    options?: RequestOptions & {
      acceptHeaderOverride?: ActivityStreamGlobalFeedAcceptEnum;
    },
  ): Promise<operations.ActivityStreamGlobalFeedResponse> {
    return unwrapAsync(activityActivityStreamGlobalFeed(
      this,
      options,
    ));
  }
}
