/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { badgePricingSearch } from "../funcs/badgePricingSearch.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class BadgePricing extends ClientSDK {
  /**
   * Search the badge-pricing catalog
   */
  async search(
    request: operations.BadgePricingSearchRequest,
    options?: RequestOptions,
  ): Promise<operations.BadgePricingSearchResponse> {
    return unwrapAsync(badgePricingSearch(
      this,
      request,
      options,
    ));
  }
}
