/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { badgeBadgeListAccounts } from "../funcs/badgeBadgeListAccounts.js";
import { badgeSearch } from "../funcs/badgeSearch.js";
import { badgeSuggestTags } from "../funcs/badgeSuggestTags.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Badge extends ClientSDK {
  async badgeListAccounts(
    request: components.V1BadgeListAccountsRequestBody,
    options?: RequestOptions,
  ): Promise<operations.BadgeListAccountsResponse> {
    return unwrapAsync(badgeBadgeListAccounts(
      this,
      request,
      options,
    ));
  }

  async search(
    request: components.V1SearchRequest,
    options?: RequestOptions,
  ): Promise<operations.BadgeSearchBadgesResponse> {
    return unwrapAsync(badgeSearch(
      this,
      request,
      options,
    ));
  }

  async suggestTags(
    request: components.V1BadgeSuggestTagsRequestBody,
    options?: RequestOptions,
  ): Promise<operations.BadgeSuggestTagsResponse> {
    return unwrapAsync(badgeSuggestTags(
      this,
      request,
      options,
    ));
  }
}
