/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { developerAccountV1SettingsDeveloperAppCreate } from "../funcs/developerAccountV1SettingsDeveloperAppCreate.js";
import { developerAccountV1SettingsDeveloperAppDelete } from "../funcs/developerAccountV1SettingsDeveloperAppDelete.js";
import { developerAccountV1SettingsDeveloperAppUpdate } from "../funcs/developerAccountV1SettingsDeveloperAppUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Developer extends ClientSDK {
  async accountV1SettingsDeveloperAppCreate(
    request: components.V1DeveloperAppCreateRequestBody,
    options?: RequestOptions,
  ): Promise<operations.AccountV1SettingsDeveloperAppCreateResponse> {
    return unwrapAsync(developerAccountV1SettingsDeveloperAppCreate(
      this,
      request,
      options,
    ));
  }

  async accountV1SettingsDeveloperAppDelete(
    request: components.V1AccountDeveloperAppDeleteRequestBody,
    options?: RequestOptions,
  ): Promise<operations.AccountV1SettingsDeveloperAppDeleteResponse> {
    return unwrapAsync(developerAccountV1SettingsDeveloperAppDelete(
      this,
      request,
      options,
    ));
  }

  async accountV1SettingsDeveloperAppUpdate(
    request: components.V1AccountDeveloperAppUpdateRequestBody,
    options?: RequestOptions,
  ): Promise<operations.AccountV1SettingsDeveloperAppUpdateResponse> {
    return unwrapAsync(developerAccountV1SettingsDeveloperAppUpdate(
      this,
      request,
      options,
    ));
  }
}
