/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { groupQueueUpdate } from "../funcs/groupQueueUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Group extends ClientSDK {
  /**
   * Queue group update
   */
  async queueUpdate(
    request: components.V1GroupQueueUpdateRequestBody,
    options?: RequestOptions,
  ): Promise<operations.GroupQueueUpdateResponse> {
    return unwrapAsync(groupQueueUpdate(
      this,
      request,
      options,
    ));
  }
}
