/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { imagesGet } from "../funcs/imagesGet.js";
import { imagesUpdate } from "../funcs/imagesUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Images extends ClientSDK {
  async get(
    options?: RequestOptions,
  ): Promise<operations.AccountV1ImagesGetResponse> {
    return unwrapAsync(imagesGet(
      this,
      options,
    ));
  }

  async update(
    request: components.V1UpdateImageRequestBody,
    options?: RequestOptions,
  ): Promise<operations.AccountV1ImagesUpdateResponse> {
    return unwrapAsync(imagesUpdate(
      this,
      request,
      options,
    ));
  }
}
