/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { leaderboardGetAccount } from "../funcs/leaderboardGetAccount.js";
import { leaderboardGetAccountsMeta } from "../funcs/leaderboardGetAccountsMeta.js";
import { leaderboardGetGroup } from "../funcs/leaderboardGetGroup.js";
import { leaderboardGetGroupsMeta } from "../funcs/leaderboardGetGroupsMeta.js";
import { leaderboardGetLowestRanks } from "../funcs/leaderboardGetLowestRanks.js";
import { leaderboardPreviewAccountRank } from "../funcs/leaderboardPreviewAccountRank.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Leaderboard extends ClientSDK {
  /**
   * Get account leaderboard
   */
  async getAccount(
    request: components.V1LeaderboardGetAccountLeaderboardRequestBody,
    options?: RequestOptions,
  ): Promise<operations.LeaderboardGetAccountLeaderboardResponse> {
    return unwrapAsync(leaderboardGetAccount(
      this,
      request,
      options,
    ));
  }

  /**
   * Get accounts leaderboard metadata
   */
  async getAccountsMeta(
    request: components.V1LeaderboardGetAccountsMetaRequestBody,
    options?: RequestOptions,
  ): Promise<operations.LeaderboardGetAccountsMetaResponse> {
    return unwrapAsync(leaderboardGetAccountsMeta(
      this,
      request,
      options,
    ));
  }

  /**
   * Get group leaderboard
   */
  async getGroup(
    request: components.V1LeaderboardGetGroupLeaderboardRequestBody,
    options?: RequestOptions,
  ): Promise<operations.LeaderboardGetGroupLeaderboardResponse> {
    return unwrapAsync(leaderboardGetGroup(
      this,
      request,
      options,
    ));
  }

  /**
   * Get groups leaderboard metadata
   */
  async getGroupsMeta(
    request: components.V1LeaderboardGetGroupsMetaRequestBody,
    options?: RequestOptions,
  ): Promise<operations.LeaderboardGetGroupsMetaResponse> {
    return unwrapAsync(leaderboardGetGroupsMeta(
      this,
      request,
      options,
    ));
  }

  /**
   * Get lowest ranked accounts
   */
  async getLowestRanks(
    request: components.V1LeaderboardGetLowestRanksRequestBody,
    options?: RequestOptions,
  ): Promise<operations.LeaderboardGetLowestRanksResponse> {
    return unwrapAsync(leaderboardGetLowestRanks(
      this,
      request,
      options,
    ));
  }

  /**
   * Preview account rank
   */
  async previewAccountRank(
    request: components.V1LeaderboardPreviewAccountRankRequestBody,
    options?: RequestOptions,
  ): Promise<operations.LeaderboardPreviewAccountRankResponse> {
    return unwrapAsync(leaderboardPreviewAccountRank(
      this,
      request,
      options,
    ));
  }
}
