/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metaAccountV1GetEmbed } from "../funcs/metaAccountV1GetEmbed.js";
import { metaAccountV1GetMeta } from "../funcs/metaAccountV1GetMeta.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Meta extends ClientSDK {
  async accountV1GetEmbed(
    request: components.AccountSearch,
    options?: RequestOptions,
  ): Promise<operations.AccountV1GetEmbedResponse> {
    return unwrapAsync(metaAccountV1GetEmbed(
      this,
      request,
      options,
    ));
  }

  async accountV1GetMeta(
    request: components.AccountSearch,
    options?: RequestOptions,
  ): Promise<operations.AccountV1GetMetaResponse> {
    return unwrapAsync(metaAccountV1GetMeta(
      this,
      request,
      options,
    ));
  }
}
