/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { staffList } from "../funcs/staffList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Staff extends ClientSDK {
  async list(
    options?: RequestOptions,
  ): Promise<operations.StaffListStaffResponse> {
    return unwrapAsync(staffList(
      this,
      options,
    ));
  }
}
