/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { vanityVerify } from "../funcs/vanityVerify.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Vanity extends ClientSDK {
  /**
   * Live-verify a Steam vanity URL against Steam
   */
  async verify(
    request: operations.VanityVerifyRequest,
    options?: RequestOptions,
  ): Promise<operations.VanityVerifyResponse> {
    return unwrapAsync(vanityVerify(
      this,
      request,
      options,
    ));
  }
}
