workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    API:
        inputs:
            - location: http://127.0.0.1:7388/openapi.json
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/steamsets/steamsets/api
targets:
    steam-sets:
        target: typescript
        source: API
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/steamsets/steamsets/api-typescript-code-samples
            blocking: false
