workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    API:
        inputs:
            - location: https://api.steamsets.com/openapi.json
targets:
    steam-sets:
        target: typescript
        source: API
        publish:
            npm:
                token: $npm_token
