/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AccountGetDataPointsResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1AccountGetDataPointsResponseBody?:
    | components.V1AccountGetDataPointsResponseBody
    | undefined;
};

/** @internal */
export const AccountGetDataPointsResponse$inboundSchema: z.ZodMiniType<
  AccountGetDataPointsResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    V1AccountGetDataPointsResponseBody: z.optional(
      components.V1AccountGetDataPointsResponseBody$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "V1AccountGetDataPointsResponseBody":
        "v1AccountGetDataPointsResponseBody",
    });
  }),
);

export function accountGetDataPointsResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountGetDataPointsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountGetDataPointsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountGetDataPointsResponse' from JSON`,
  );
}
