/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AccountUpdateDeveloperAppResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1AccountDeveloperAppUpdateResponseBody?:
    | components.V1AccountDeveloperAppUpdateResponseBody
    | undefined;
};

/** @internal */
export const AccountUpdateDeveloperAppResponse$inboundSchema: z.ZodType<
  AccountUpdateDeveloperAppResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V1AccountDeveloperAppUpdateResponseBody: components
    .V1AccountDeveloperAppUpdateResponseBody$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V1AccountDeveloperAppUpdateResponseBody":
      "v1AccountDeveloperAppUpdateResponseBody",
  });
});

/** @internal */
export type AccountUpdateDeveloperAppResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  V1AccountDeveloperAppUpdateResponseBody?:
    | components.V1AccountDeveloperAppUpdateResponseBody$Outbound
    | undefined;
};

/** @internal */
export const AccountUpdateDeveloperAppResponse$outboundSchema: z.ZodType<
  AccountUpdateDeveloperAppResponse$Outbound,
  z.ZodTypeDef,
  AccountUpdateDeveloperAppResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  v1AccountDeveloperAppUpdateResponseBody: components
    .V1AccountDeveloperAppUpdateResponseBody$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    v1AccountDeveloperAppUpdateResponseBody:
      "V1AccountDeveloperAppUpdateResponseBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AccountUpdateDeveloperAppResponse$ {
  /** @deprecated use `AccountUpdateDeveloperAppResponse$inboundSchema` instead. */
  export const inboundSchema = AccountUpdateDeveloperAppResponse$inboundSchema;
  /** @deprecated use `AccountUpdateDeveloperAppResponse$outboundSchema` instead. */
  export const outboundSchema =
    AccountUpdateDeveloperAppResponse$outboundSchema;
  /** @deprecated use `AccountUpdateDeveloperAppResponse$Outbound` instead. */
  export type Outbound = AccountUpdateDeveloperAppResponse$Outbound;
}

export function accountUpdateDeveloperAppResponseToJSON(
  accountUpdateDeveloperAppResponse: AccountUpdateDeveloperAppResponse,
): string {
  return JSON.stringify(
    AccountUpdateDeveloperAppResponse$outboundSchema.parse(
      accountUpdateDeveloperAppResponse,
    ),
  );
}

export function accountUpdateDeveloperAppResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountUpdateDeveloperAppResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountUpdateDeveloperAppResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountUpdateDeveloperAppResponse' from JSON`,
  );
}
