/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AccountV1SettingsDeleteImagesResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1DeleteImagesResponseBody?:
    | components.V1DeleteImagesResponseBody
    | undefined;
};

/** @internal */
export const AccountV1SettingsDeleteImagesResponse$inboundSchema: z.ZodType<
  AccountV1SettingsDeleteImagesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V1DeleteImagesResponseBody: components
    .V1DeleteImagesResponseBody$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V1DeleteImagesResponseBody": "v1DeleteImagesResponseBody",
  });
});

/** @internal */
export type AccountV1SettingsDeleteImagesResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  V1DeleteImagesResponseBody?:
    | components.V1DeleteImagesResponseBody$Outbound
    | undefined;
};

/** @internal */
export const AccountV1SettingsDeleteImagesResponse$outboundSchema: z.ZodType<
  AccountV1SettingsDeleteImagesResponse$Outbound,
  z.ZodTypeDef,
  AccountV1SettingsDeleteImagesResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  v1DeleteImagesResponseBody: components
    .V1DeleteImagesResponseBody$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    v1DeleteImagesResponseBody: "V1DeleteImagesResponseBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AccountV1SettingsDeleteImagesResponse$ {
  /** @deprecated use `AccountV1SettingsDeleteImagesResponse$inboundSchema` instead. */
  export const inboundSchema =
    AccountV1SettingsDeleteImagesResponse$inboundSchema;
  /** @deprecated use `AccountV1SettingsDeleteImagesResponse$outboundSchema` instead. */
  export const outboundSchema =
    AccountV1SettingsDeleteImagesResponse$outboundSchema;
  /** @deprecated use `AccountV1SettingsDeleteImagesResponse$Outbound` instead. */
  export type Outbound = AccountV1SettingsDeleteImagesResponse$Outbound;
}

export function accountV1SettingsDeleteImagesResponseToJSON(
  accountV1SettingsDeleteImagesResponse: AccountV1SettingsDeleteImagesResponse,
): string {
  return JSON.stringify(
    AccountV1SettingsDeleteImagesResponse$outboundSchema.parse(
      accountV1SettingsDeleteImagesResponse,
    ),
  );
}

export function accountV1SettingsDeleteImagesResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountV1SettingsDeleteImagesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AccountV1SettingsDeleteImagesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountV1SettingsDeleteImagesResponse' from JSON`,
  );
}
