/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AccountUpdateProgressResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1AccountUpdateProgressResponseBody?:
    | components.V1AccountUpdateProgressResponseBody
    | undefined;
};

/** @internal */
export const AccountUpdateProgressResponse$inboundSchema: z.ZodMiniType<
  AccountUpdateProgressResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    V1AccountUpdateProgressResponseBody: z.optional(
      components.V1AccountUpdateProgressResponseBody$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "V1AccountUpdateProgressResponseBody":
        "v1AccountUpdateProgressResponseBody",
    });
  }),
);

export function accountUpdateProgressResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountUpdateProgressResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountUpdateProgressResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountUpdateProgressResponse' from JSON`,
  );
}
