/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AccountV1SettingsGetResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1GetSettingsBody?: components.V1GetSettingsBody | undefined;
};

/** @internal */
export const AccountV1SettingsGetResponse$inboundSchema: z.ZodType<
  AccountV1SettingsGetResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V1GetSettingsBody: components.V1GetSettingsBody$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V1GetSettingsBody": "v1GetSettingsBody",
  });
});

/** @internal */
export type AccountV1SettingsGetResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  V1GetSettingsBody?: components.V1GetSettingsBody$Outbound | undefined;
};

/** @internal */
export const AccountV1SettingsGetResponse$outboundSchema: z.ZodType<
  AccountV1SettingsGetResponse$Outbound,
  z.ZodTypeDef,
  AccountV1SettingsGetResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  v1GetSettingsBody: components.V1GetSettingsBody$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    v1GetSettingsBody: "V1GetSettingsBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AccountV1SettingsGetResponse$ {
  /** @deprecated use `AccountV1SettingsGetResponse$inboundSchema` instead. */
  export const inboundSchema = AccountV1SettingsGetResponse$inboundSchema;
  /** @deprecated use `AccountV1SettingsGetResponse$outboundSchema` instead. */
  export const outboundSchema = AccountV1SettingsGetResponse$outboundSchema;
  /** @deprecated use `AccountV1SettingsGetResponse$Outbound` instead. */
  export type Outbound = AccountV1SettingsGetResponse$Outbound;
}

export function accountV1SettingsGetResponseToJSON(
  accountV1SettingsGetResponse: AccountV1SettingsGetResponse,
): string {
  return JSON.stringify(
    AccountV1SettingsGetResponse$outboundSchema.parse(
      accountV1SettingsGetResponse,
    ),
  );
}

export function accountV1SettingsGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountV1SettingsGetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountV1SettingsGetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountV1SettingsGetResponse' from JSON`,
  );
}
