/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AccountCreateDeveloperAppResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1AccountCreateDeveloperAppResponseBody?:
    | components.V1AccountCreateDeveloperAppResponseBody
    | undefined;
};

/** @internal */
export const AccountCreateDeveloperAppResponse$inboundSchema: z.ZodMiniType<
  AccountCreateDeveloperAppResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    V1AccountCreateDeveloperAppResponseBody: z.optional(
      components.V1AccountCreateDeveloperAppResponseBody$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "V1AccountCreateDeveloperAppResponseBody":
        "v1AccountCreateDeveloperAppResponseBody",
    });
  }),
);

export function accountCreateDeveloperAppResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountCreateDeveloperAppResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountCreateDeveloperAppResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountCreateDeveloperAppResponse' from JSON`,
  );
}
