/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AccountLoginRequest = {
  userAgent?: string | undefined;
  xForwardedFor?: string | undefined;
  loginRequestBody: components.LoginRequestBody;
};

export type AccountLoginResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1AccountLoginResponseBody?:
    | components.V1AccountLoginResponseBody
    | undefined;
};

/** @internal */
export type AccountLoginRequest$Outbound = {
  "User-Agent"?: string | undefined;
  "X-Forwarded-For"?: string | undefined;
  LoginRequestBody: components.LoginRequestBody$Outbound;
};

/** @internal */
export const AccountLoginRequest$outboundSchema: z.ZodMiniType<
  AccountLoginRequest$Outbound,
  AccountLoginRequest
> = z.pipe(
  z.object({
    userAgent: z.optional(z.string()),
    xForwardedFor: z.optional(z.string()),
    loginRequestBody: components.LoginRequestBody$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      userAgent: "User-Agent",
      xForwardedFor: "X-Forwarded-For",
      loginRequestBody: "LoginRequestBody",
    });
  }),
);

export function accountLoginRequestToJSON(
  accountLoginRequest: AccountLoginRequest,
): string {
  return JSON.stringify(
    AccountLoginRequest$outboundSchema.parse(accountLoginRequest),
  );
}

/** @internal */
export const AccountLoginResponse$inboundSchema: z.ZodMiniType<
  AccountLoginResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    V1AccountLoginResponseBody: z.optional(
      components.V1AccountLoginResponseBody$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "V1AccountLoginResponseBody": "v1AccountLoginResponseBody",
    });
  }),
);

export function accountLoginResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountLoginResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountLoginResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountLoginResponse' from JSON`,
  );
}
