/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AccountV1GetOwnedBadgesResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1AccountBadgeOwnedBadgesResponseBody?:
    | components.V1AccountBadgeOwnedBadgesResponseBody
    | undefined;
};

/** @internal */
export const AccountV1GetOwnedBadgesResponse$inboundSchema: z.ZodType<
  AccountV1GetOwnedBadgesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V1AccountBadgeOwnedBadgesResponseBody: components
    .V1AccountBadgeOwnedBadgesResponseBody$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V1AccountBadgeOwnedBadgesResponseBody":
      "v1AccountBadgeOwnedBadgesResponseBody",
  });
});

/** @internal */
export type AccountV1GetOwnedBadgesResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  V1AccountBadgeOwnedBadgesResponseBody?:
    | components.V1AccountBadgeOwnedBadgesResponseBody$Outbound
    | undefined;
};

/** @internal */
export const AccountV1GetOwnedBadgesResponse$outboundSchema: z.ZodType<
  AccountV1GetOwnedBadgesResponse$Outbound,
  z.ZodTypeDef,
  AccountV1GetOwnedBadgesResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  v1AccountBadgeOwnedBadgesResponseBody: components
    .V1AccountBadgeOwnedBadgesResponseBody$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    v1AccountBadgeOwnedBadgesResponseBody:
      "V1AccountBadgeOwnedBadgesResponseBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AccountV1GetOwnedBadgesResponse$ {
  /** @deprecated use `AccountV1GetOwnedBadgesResponse$inboundSchema` instead. */
  export const inboundSchema = AccountV1GetOwnedBadgesResponse$inboundSchema;
  /** @deprecated use `AccountV1GetOwnedBadgesResponse$outboundSchema` instead. */
  export const outboundSchema = AccountV1GetOwnedBadgesResponse$outboundSchema;
  /** @deprecated use `AccountV1GetOwnedBadgesResponse$Outbound` instead. */
  export type Outbound = AccountV1GetOwnedBadgesResponse$Outbound;
}

export function accountV1GetOwnedBadgesResponseToJSON(
  accountV1GetOwnedBadgesResponse: AccountV1GetOwnedBadgesResponse,
): string {
  return JSON.stringify(
    AccountV1GetOwnedBadgesResponse$outboundSchema.parse(
      accountV1GetOwnedBadgesResponse,
    ),
  );
}

export function accountV1GetOwnedBadgesResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountV1GetOwnedBadgesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountV1GetOwnedBadgesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountV1GetOwnedBadgesResponse' from JSON`,
  );
}
