/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type AccountV1GetFriendsRequest = {
  xForwardedFor?: string | undefined;
  userAgent?: string | undefined;
  accountSearch: components.AccountSearch;
};

export type AccountV1GetFriendsResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1AccountFriendsResponseBody?:
    | components.V1AccountFriendsResponseBody
    | undefined;
};

/** @internal */
export const AccountV1GetFriendsRequest$inboundSchema: z.ZodType<
  AccountV1GetFriendsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  "X-Forwarded-For": z.string().optional(),
  "User-Agent": z.string().optional(),
  AccountSearch: components.AccountSearch$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "X-Forwarded-For": "xForwardedFor",
    "User-Agent": "userAgent",
    "AccountSearch": "accountSearch",
  });
});

/** @internal */
export type AccountV1GetFriendsRequest$Outbound = {
  "X-Forwarded-For"?: string | undefined;
  "User-Agent"?: string | undefined;
  AccountSearch: components.AccountSearch$Outbound;
};

/** @internal */
export const AccountV1GetFriendsRequest$outboundSchema: z.ZodType<
  AccountV1GetFriendsRequest$Outbound,
  z.ZodTypeDef,
  AccountV1GetFriendsRequest
> = z.object({
  xForwardedFor: z.string().optional(),
  userAgent: z.string().optional(),
  accountSearch: components.AccountSearch$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    xForwardedFor: "X-Forwarded-For",
    userAgent: "User-Agent",
    accountSearch: "AccountSearch",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AccountV1GetFriendsRequest$ {
  /** @deprecated use `AccountV1GetFriendsRequest$inboundSchema` instead. */
  export const inboundSchema = AccountV1GetFriendsRequest$inboundSchema;
  /** @deprecated use `AccountV1GetFriendsRequest$outboundSchema` instead. */
  export const outboundSchema = AccountV1GetFriendsRequest$outboundSchema;
  /** @deprecated use `AccountV1GetFriendsRequest$Outbound` instead. */
  export type Outbound = AccountV1GetFriendsRequest$Outbound;
}

/** @internal */
export const AccountV1GetFriendsResponse$inboundSchema: z.ZodType<
  AccountV1GetFriendsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V1AccountFriendsResponseBody: components
    .V1AccountFriendsResponseBody$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V1AccountFriendsResponseBody": "v1AccountFriendsResponseBody",
  });
});

/** @internal */
export type AccountV1GetFriendsResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  V1AccountFriendsResponseBody?:
    | components.V1AccountFriendsResponseBody$Outbound
    | undefined;
};

/** @internal */
export const AccountV1GetFriendsResponse$outboundSchema: z.ZodType<
  AccountV1GetFriendsResponse$Outbound,
  z.ZodTypeDef,
  AccountV1GetFriendsResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  v1AccountFriendsResponseBody: components
    .V1AccountFriendsResponseBody$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    v1AccountFriendsResponseBody: "V1AccountFriendsResponseBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AccountV1GetFriendsResponse$ {
  /** @deprecated use `AccountV1GetFriendsResponse$inboundSchema` instead. */
  export const inboundSchema = AccountV1GetFriendsResponse$inboundSchema;
  /** @deprecated use `AccountV1GetFriendsResponse$outboundSchema` instead. */
  export const outboundSchema = AccountV1GetFriendsResponse$outboundSchema;
  /** @deprecated use `AccountV1GetFriendsResponse$Outbound` instead. */
  export type Outbound = AccountV1GetFriendsResponse$Outbound;
}
