/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AccountSendTestPushResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  accountSendTestPushResponseBody?:
    | components.AccountSendTestPushResponseBody
    | undefined;
};

/** @internal */
export const AccountSendTestPushResponse$inboundSchema: z.ZodMiniType<
  AccountSendTestPushResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    AccountSendTestPushResponseBody: z.optional(
      components.AccountSendTestPushResponseBody$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "AccountSendTestPushResponseBody": "accountSendTestPushResponseBody",
    });
  }),
);

export function accountSendTestPushResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountSendTestPushResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountSendTestPushResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountSendTestPushResponse' from JSON`,
  );
}
