/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AccountUpdateConnectionResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1AccountUpdateConnectionResponseBody?:
    | components.V1AccountUpdateConnectionResponseBody
    | undefined;
};

/** @internal */
export const AccountUpdateConnectionResponse$inboundSchema: z.ZodType<
  AccountUpdateConnectionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V1AccountUpdateConnectionResponseBody: components
    .V1AccountUpdateConnectionResponseBody$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V1AccountUpdateConnectionResponseBody":
      "v1AccountUpdateConnectionResponseBody",
  });
});

/** @internal */
export type AccountUpdateConnectionResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  V1AccountUpdateConnectionResponseBody?:
    | components.V1AccountUpdateConnectionResponseBody$Outbound
    | undefined;
};

/** @internal */
export const AccountUpdateConnectionResponse$outboundSchema: z.ZodType<
  AccountUpdateConnectionResponse$Outbound,
  z.ZodTypeDef,
  AccountUpdateConnectionResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  v1AccountUpdateConnectionResponseBody: components
    .V1AccountUpdateConnectionResponseBody$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    v1AccountUpdateConnectionResponseBody:
      "V1AccountUpdateConnectionResponseBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AccountUpdateConnectionResponse$ {
  /** @deprecated use `AccountUpdateConnectionResponse$inboundSchema` instead. */
  export const inboundSchema = AccountUpdateConnectionResponse$inboundSchema;
  /** @deprecated use `AccountUpdateConnectionResponse$outboundSchema` instead. */
  export const outboundSchema = AccountUpdateConnectionResponse$outboundSchema;
  /** @deprecated use `AccountUpdateConnectionResponse$Outbound` instead. */
  export type Outbound = AccountUpdateConnectionResponse$Outbound;
}

export function accountUpdateConnectionResponseToJSON(
  accountUpdateConnectionResponse: AccountUpdateConnectionResponse,
): string {
  return JSON.stringify(
    AccountUpdateConnectionResponse$outboundSchema.parse(
      accountUpdateConnectionResponse,
    ),
  );
}

export function accountUpdateConnectionResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountUpdateConnectionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountUpdateConnectionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountUpdateConnectionResponse' from JSON`,
  );
}
