/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type AccountV1LeaderboardPreviewResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1AccountLeaderboardPreviewResponseBody?:
    | components.V1AccountLeaderboardPreviewResponseBody
    | undefined;
};

/** @internal */
export const AccountV1LeaderboardPreviewResponse$inboundSchema: z.ZodType<
  AccountV1LeaderboardPreviewResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V1AccountLeaderboardPreviewResponseBody: components
    .V1AccountLeaderboardPreviewResponseBody$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V1AccountLeaderboardPreviewResponseBody":
      "v1AccountLeaderboardPreviewResponseBody",
  });
});

/** @internal */
export type AccountV1LeaderboardPreviewResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  V1AccountLeaderboardPreviewResponseBody?:
    | components.V1AccountLeaderboardPreviewResponseBody$Outbound
    | undefined;
};

/** @internal */
export const AccountV1LeaderboardPreviewResponse$outboundSchema: z.ZodType<
  AccountV1LeaderboardPreviewResponse$Outbound,
  z.ZodTypeDef,
  AccountV1LeaderboardPreviewResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  v1AccountLeaderboardPreviewResponseBody: components
    .V1AccountLeaderboardPreviewResponseBody$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    v1AccountLeaderboardPreviewResponseBody:
      "V1AccountLeaderboardPreviewResponseBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AccountV1LeaderboardPreviewResponse$ {
  /** @deprecated use `AccountV1LeaderboardPreviewResponse$inboundSchema` instead. */
  export const inboundSchema =
    AccountV1LeaderboardPreviewResponse$inboundSchema;
  /** @deprecated use `AccountV1LeaderboardPreviewResponse$outboundSchema` instead. */
  export const outboundSchema =
    AccountV1LeaderboardPreviewResponse$outboundSchema;
  /** @deprecated use `AccountV1LeaderboardPreviewResponse$Outbound` instead. */
  export type Outbound = AccountV1LeaderboardPreviewResponse$Outbound;
}
