/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AccountGetBadgeStatsResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1AccountBadgeStats?: components.V1AccountBadgeStats | undefined;
};

/** @internal */
export const AccountGetBadgeStatsResponse$inboundSchema: z.ZodMiniType<
  AccountGetBadgeStatsResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    V1AccountBadgeStats: z.optional(
      components.V1AccountBadgeStats$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "V1AccountBadgeStats": "v1AccountBadgeStats",
    });
  }),
);

export function accountGetBadgeStatsResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountGetBadgeStatsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountGetBadgeStatsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountGetBadgeStatsResponse' from JSON`,
  );
}
