/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AccountV1SettingsEmailVerifyResponse = {
  httpMeta: components.HTTPMetadata;
  headers: { [k: string]: Array<string> };
};

/** @internal */
export const AccountV1SettingsEmailVerifyResponse$inboundSchema: z.ZodType<
  AccountV1SettingsEmailVerifyResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  Headers: z.record(z.array(z.string())),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "Headers": "headers",
  });
});

/** @internal */
export type AccountV1SettingsEmailVerifyResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  Headers: { [k: string]: Array<string> };
};

/** @internal */
export const AccountV1SettingsEmailVerifyResponse$outboundSchema: z.ZodType<
  AccountV1SettingsEmailVerifyResponse$Outbound,
  z.ZodTypeDef,
  AccountV1SettingsEmailVerifyResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  headers: z.record(z.array(z.string())),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    headers: "Headers",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AccountV1SettingsEmailVerifyResponse$ {
  /** @deprecated use `AccountV1SettingsEmailVerifyResponse$inboundSchema` instead. */
  export const inboundSchema =
    AccountV1SettingsEmailVerifyResponse$inboundSchema;
  /** @deprecated use `AccountV1SettingsEmailVerifyResponse$outboundSchema` instead. */
  export const outboundSchema =
    AccountV1SettingsEmailVerifyResponse$outboundSchema;
  /** @deprecated use `AccountV1SettingsEmailVerifyResponse$Outbound` instead. */
  export type Outbound = AccountV1SettingsEmailVerifyResponse$Outbound;
}

export function accountV1SettingsEmailVerifyResponseToJSON(
  accountV1SettingsEmailVerifyResponse: AccountV1SettingsEmailVerifyResponse,
): string {
  return JSON.stringify(
    AccountV1SettingsEmailVerifyResponse$outboundSchema.parse(
      accountV1SettingsEmailVerifyResponse,
    ),
  );
}

export function accountV1SettingsEmailVerifyResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountV1SettingsEmailVerifyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AccountV1SettingsEmailVerifyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountV1SettingsEmailVerifyResponse' from JSON`,
  );
}
