/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AccountDeleteNotificationsResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  accountDeleteNotificationsResponseBody?:
    | components.AccountDeleteNotificationsResponseBody
    | undefined;
};

/** @internal */
export const AccountDeleteNotificationsResponse$inboundSchema: z.ZodMiniType<
  AccountDeleteNotificationsResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    AccountDeleteNotificationsResponseBody: z.optional(
      components.AccountDeleteNotificationsResponseBody$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "AccountDeleteNotificationsResponseBody":
        "accountDeleteNotificationsResponseBody",
    });
  }),
);

export function accountDeleteNotificationsResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountDeleteNotificationsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AccountDeleteNotificationsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountDeleteNotificationsResponse' from JSON`,
  );
}
