/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AccountListNotificationsResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  accountListNotificationsResponseBody?:
    | components.AccountListNotificationsResponseBody
    | undefined;
};

/** @internal */
export const AccountListNotificationsResponse$inboundSchema: z.ZodMiniType<
  AccountListNotificationsResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    AccountListNotificationsResponseBody: z.optional(
      components.AccountListNotificationsResponseBody$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "AccountListNotificationsResponseBody":
        "accountListNotificationsResponseBody",
    });
  }),
);

export function accountListNotificationsResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountListNotificationsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountListNotificationsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountListNotificationsResponse' from JSON`,
  );
}
