/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AccountV1ImagesUploadResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1UploadImagesResponseBody?:
    | components.V1UploadImagesResponseBody
    | undefined;
};

/** @internal */
export const AccountV1ImagesUploadResponse$inboundSchema: z.ZodType<
  AccountV1ImagesUploadResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V1UploadImagesResponseBody: components
    .V1UploadImagesResponseBody$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V1UploadImagesResponseBody": "v1UploadImagesResponseBody",
  });
});

/** @internal */
export type AccountV1ImagesUploadResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  V1UploadImagesResponseBody?:
    | components.V1UploadImagesResponseBody$Outbound
    | undefined;
};

/** @internal */
export const AccountV1ImagesUploadResponse$outboundSchema: z.ZodType<
  AccountV1ImagesUploadResponse$Outbound,
  z.ZodTypeDef,
  AccountV1ImagesUploadResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  v1UploadImagesResponseBody: components
    .V1UploadImagesResponseBody$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    v1UploadImagesResponseBody: "V1UploadImagesResponseBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AccountV1ImagesUploadResponse$ {
  /** @deprecated use `AccountV1ImagesUploadResponse$inboundSchema` instead. */
  export const inboundSchema = AccountV1ImagesUploadResponse$inboundSchema;
  /** @deprecated use `AccountV1ImagesUploadResponse$outboundSchema` instead. */
  export const outboundSchema = AccountV1ImagesUploadResponse$outboundSchema;
  /** @deprecated use `AccountV1ImagesUploadResponse$Outbound` instead. */
  export type Outbound = AccountV1ImagesUploadResponse$Outbound;
}

export function accountV1ImagesUploadResponseToJSON(
  accountV1ImagesUploadResponse: AccountV1ImagesUploadResponse,
): string {
  return JSON.stringify(
    AccountV1ImagesUploadResponse$outboundSchema.parse(
      accountV1ImagesUploadResponse,
    ),
  );
}

export function accountV1ImagesUploadResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountV1ImagesUploadResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountV1ImagesUploadResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountV1ImagesUploadResponse' from JSON`,
  );
}
