/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AccountUploadImagesResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1AccountUploadImagesResponseBody?:
    | components.V1AccountUploadImagesResponseBody
    | undefined;
};

/** @internal */
export const AccountUploadImagesResponse$inboundSchema: z.ZodType<
  AccountUploadImagesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V1AccountUploadImagesResponseBody: components
    .V1AccountUploadImagesResponseBody$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V1AccountUploadImagesResponseBody": "v1AccountUploadImagesResponseBody",
  });
});

export function accountUploadImagesResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountUploadImagesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountUploadImagesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountUploadImagesResponse' from JSON`,
  );
}
