/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AccountMarkNotificationsReadResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  accountMarkNotificationsReadResponseBody?:
    | components.AccountMarkNotificationsReadResponseBody
    | undefined;
};

/** @internal */
export const AccountMarkNotificationsReadResponse$inboundSchema: z.ZodMiniType<
  AccountMarkNotificationsReadResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    AccountMarkNotificationsReadResponseBody: z.optional(
      components.AccountMarkNotificationsReadResponseBody$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "AccountMarkNotificationsReadResponseBody":
        "accountMarkNotificationsReadResponseBody",
    });
  }),
);

export function accountMarkNotificationsReadResponseFromJSON(
  jsonString: string,
): SafeParseResult<AccountMarkNotificationsReadResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AccountMarkNotificationsReadResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountMarkNotificationsReadResponse' from JSON`,
  );
}
