/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AdminListHiddenAccountsResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1AdminListHiddenAccountsResponseBody?:
    | components.V1AdminListHiddenAccountsResponseBody
    | undefined;
};

/** @internal */
export const AdminListHiddenAccountsResponse$inboundSchema: z.ZodMiniType<
  AdminListHiddenAccountsResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    V1AdminListHiddenAccountsResponseBody: z.optional(
      components.V1AdminListHiddenAccountsResponseBody$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "V1AdminListHiddenAccountsResponseBody":
        "v1AdminListHiddenAccountsResponseBody",
    });
  }),
);

export function adminListHiddenAccountsResponseFromJSON(
  jsonString: string,
): SafeParseResult<AdminListHiddenAccountsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AdminListHiddenAccountsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AdminListHiddenAccountsResponse' from JSON`,
  );
}
