/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AdminExportSteamApiKeysResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1AdminExportSteamApiKeysResponseBody?:
    | components.V1AdminExportSteamApiKeysResponseBody
    | undefined;
};

/** @internal */
export const AdminExportSteamApiKeysResponse$inboundSchema: z.ZodMiniType<
  AdminExportSteamApiKeysResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    V1AdminExportSteamApiKeysResponseBody: z.optional(
      components.V1AdminExportSteamApiKeysResponseBody$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "V1AdminExportSteamApiKeysResponseBody":
        "v1AdminExportSteamApiKeysResponseBody",
    });
  }),
);

export function adminExportSteamApiKeysResponseFromJSON(
  jsonString: string,
): SafeParseResult<AdminExportSteamApiKeysResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AdminExportSteamApiKeysResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AdminExportSteamApiKeysResponse' from JSON`,
  );
}
