/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AdminRemoveVanityResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1AdminRemoveVanityResponseBody?:
    | components.V1AdminRemoveVanityResponseBody
    | undefined;
};

/** @internal */
export const AdminRemoveVanityResponse$inboundSchema: z.ZodType<
  AdminRemoveVanityResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V1AdminRemoveVanityResponseBody: components
    .V1AdminRemoveVanityResponseBody$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V1AdminRemoveVanityResponseBody": "v1AdminRemoveVanityResponseBody",
  });
});

export function adminRemoveVanityResponseFromJSON(
  jsonString: string,
): SafeParseResult<AdminRemoveVanityResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AdminRemoveVanityResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AdminRemoveVanityResponse' from JSON`,
  );
}
