/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AdminDonationsUpdateCurrencyResponse = {
  httpMeta: components.HTTPMetadata;
};

/** @internal */
export const AdminDonationsUpdateCurrencyResponse$inboundSchema: z.ZodType<
  AdminDonationsUpdateCurrencyResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
  });
});

export function adminDonationsUpdateCurrencyResponseFromJSON(
  jsonString: string,
): SafeParseResult<AdminDonationsUpdateCurrencyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AdminDonationsUpdateCurrencyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AdminDonationsUpdateCurrencyResponse' from JSON`,
  );
}
