/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AdminDonationsListCurrenciesResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1AdminDonationsListCurrenciesResponseBody?:
    | components.V1AdminDonationsListCurrenciesResponseBody
    | undefined;
};

/** @internal */
export const AdminDonationsListCurrenciesResponse$inboundSchema: z.ZodType<
  AdminDonationsListCurrenciesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V1AdminDonationsListCurrenciesResponseBody: components
    .V1AdminDonationsListCurrenciesResponseBody$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V1AdminDonationsListCurrenciesResponseBody":
      "v1AdminDonationsListCurrenciesResponseBody",
  });
});

export function adminDonationsListCurrenciesResponseFromJSON(
  jsonString: string,
): SafeParseResult<AdminDonationsListCurrenciesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AdminDonationsListCurrenciesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AdminDonationsListCurrenciesResponse' from JSON`,
  );
}
