/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AnalyticsGetDistributionResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  analyticsDistribution?: components.AnalyticsDistribution | undefined;
};

/** @internal */
export const AnalyticsGetDistributionResponse$inboundSchema: z.ZodType<
  AnalyticsGetDistributionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  AnalyticsDistribution: components.AnalyticsDistribution$inboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "AnalyticsDistribution": "analyticsDistribution",
  });
});

export function analyticsGetDistributionResponseFromJSON(
  jsonString: string,
): SafeParseResult<AnalyticsGetDistributionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnalyticsGetDistributionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnalyticsGetDistributionResponse' from JSON`,
  );
}
