/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AppListOwnersResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  appListOwnersResponseBody?: components.AppListOwnersResponseBody | undefined;
};

/** @internal */
export const AppListOwnersResponse$inboundSchema: z.ZodType<
  AppListOwnersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  AppListOwnersResponseBody: components.AppListOwnersResponseBody$inboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "AppListOwnersResponseBody": "appListOwnersResponseBody",
  });
});

export function appListOwnersResponseFromJSON(
  jsonString: string,
): SafeParseResult<AppListOwnersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AppListOwnersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppListOwnersResponse' from JSON`,
  );
}
