/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AppListBadgesResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1AppListBadgesResponseBody?:
    | components.V1AppListBadgesResponseBody
    | undefined;
};

/** @internal */
export const AppListBadgesResponse$inboundSchema: z.ZodType<
  AppListBadgesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V1AppListBadgesResponseBody: components
    .V1AppListBadgesResponseBody$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V1AppListBadgesResponseBody": "v1AppListBadgesResponseBody",
  });
});

export function appListBadgesResponseFromJSON(
  jsonString: string,
): SafeParseResult<AppListBadgesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AppListBadgesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppListBadgesResponse' from JSON`,
  );
}
