/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AppV1ListBadgesResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1AppBadgeListResponseBody?:
    | components.V1AppBadgeListResponseBody
    | undefined;
};

/** @internal */
export const AppV1ListBadgesResponse$inboundSchema: z.ZodType<
  AppV1ListBadgesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V1AppBadgeListResponseBody: components
    .V1AppBadgeListResponseBody$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V1AppBadgeListResponseBody": "v1AppBadgeListResponseBody",
  });
});

/** @internal */
export type AppV1ListBadgesResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  V1AppBadgeListResponseBody?:
    | components.V1AppBadgeListResponseBody$Outbound
    | undefined;
};

/** @internal */
export const AppV1ListBadgesResponse$outboundSchema: z.ZodType<
  AppV1ListBadgesResponse$Outbound,
  z.ZodTypeDef,
  AppV1ListBadgesResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  v1AppBadgeListResponseBody: components
    .V1AppBadgeListResponseBody$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    v1AppBadgeListResponseBody: "V1AppBadgeListResponseBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AppV1ListBadgesResponse$ {
  /** @deprecated use `AppV1ListBadgesResponse$inboundSchema` instead. */
  export const inboundSchema = AppV1ListBadgesResponse$inboundSchema;
  /** @deprecated use `AppV1ListBadgesResponse$outboundSchema` instead. */
  export const outboundSchema = AppV1ListBadgesResponse$outboundSchema;
  /** @deprecated use `AppV1ListBadgesResponse$Outbound` instead. */
  export type Outbound = AppV1ListBadgesResponse$Outbound;
}

export function appV1ListBadgesResponseToJSON(
  appV1ListBadgesResponse: AppV1ListBadgesResponse,
): string {
  return JSON.stringify(
    AppV1ListBadgesResponse$outboundSchema.parse(appV1ListBadgesResponse),
  );
}

export function appV1ListBadgesResponseFromJSON(
  jsonString: string,
): SafeParseResult<AppV1ListBadgesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AppV1ListBadgesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppV1ListBadgesResponse' from JSON`,
  );
}
