/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type BadgeListAccountsResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1BadgeListAccountsResponseBody?:
    | components.V1BadgeListAccountsResponseBody
    | undefined;
};

/** @internal */
export const BadgeListAccountsResponse$inboundSchema: z.ZodType<
  BadgeListAccountsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V1BadgeListAccountsResponseBody: components
    .V1BadgeListAccountsResponseBody$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V1BadgeListAccountsResponseBody": "v1BadgeListAccountsResponseBody",
  });
});

/** @internal */
export type BadgeListAccountsResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  V1BadgeListAccountsResponseBody?:
    | components.V1BadgeListAccountsResponseBody$Outbound
    | undefined;
};

/** @internal */
export const BadgeListAccountsResponse$outboundSchema: z.ZodType<
  BadgeListAccountsResponse$Outbound,
  z.ZodTypeDef,
  BadgeListAccountsResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  v1BadgeListAccountsResponseBody: components
    .V1BadgeListAccountsResponseBody$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    v1BadgeListAccountsResponseBody: "V1BadgeListAccountsResponseBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BadgeListAccountsResponse$ {
  /** @deprecated use `BadgeListAccountsResponse$inboundSchema` instead. */
  export const inboundSchema = BadgeListAccountsResponse$inboundSchema;
  /** @deprecated use `BadgeListAccountsResponse$outboundSchema` instead. */
  export const outboundSchema = BadgeListAccountsResponse$outboundSchema;
  /** @deprecated use `BadgeListAccountsResponse$Outbound` instead. */
  export type Outbound = BadgeListAccountsResponse$Outbound;
}

export function badgeListAccountsResponseToJSON(
  badgeListAccountsResponse: BadgeListAccountsResponse,
): string {
  return JSON.stringify(
    BadgeListAccountsResponse$outboundSchema.parse(badgeListAccountsResponse),
  );
}

export function badgeListAccountsResponseFromJSON(
  jsonString: string,
): SafeParseResult<BadgeListAccountsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BadgeListAccountsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BadgeListAccountsResponse' from JSON`,
  );
}
