/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type BadgeListTagsResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1BadgeListTagsResponseBody?:
    | components.V1BadgeListTagsResponseBody
    | undefined;
};

/** @internal */
export const BadgeListTagsResponse$inboundSchema: z.ZodMiniType<
  BadgeListTagsResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    V1BadgeListTagsResponseBody: z.optional(
      components.V1BadgeListTagsResponseBody$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "V1BadgeListTagsResponseBody": "v1BadgeListTagsResponseBody",
    });
  }),
);

export function badgeListTagsResponseFromJSON(
  jsonString: string,
): SafeParseResult<BadgeListTagsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BadgeListTagsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BadgeListTagsResponse' from JSON`,
  );
}
