/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { EventStream } from "../../lib/event-streams.js";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type EventMarketPriceTick = {
  data: components.EventMarketPriceTickData;
  /**
   * The event name.
   */
  event: "market-price-tick";
  /**
   * The event ID.
   */
  id?: string | undefined;
  /**
   * The retry time in milliseconds.
   */
  retry?: number | undefined;
};

export type ServerSentEventsEventHeartbeat = {
  data: components.PricingHeartbeat;
  /**
   * The event name.
   */
  event: "heartbeat";
  /**
   * The event ID.
   */
  id?: string | undefined;
  /**
   * The retry time in milliseconds.
   */
  retry?: number | undefined;
};

/**
 * Each oneOf object in the array represents one possible Server Sent Events (SSE) message, serialized as UTF-8 text according to the SSE specification.
 */
export type BadgePricingSubscribeServerSentEvents =
  | ServerSentEventsEventHeartbeat
  | EventMarketPriceTick;

export type BadgePricingSubscribeResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  serverSentEvents?:
    | EventStream<ServerSentEventsEventHeartbeat | EventMarketPriceTick>
    | undefined;
  /**
   * Error
   */
  errorModel?: components.ErrorModel | undefined;
};

/** @internal */
export const EventMarketPriceTick$inboundSchema: z.ZodMiniType<
  EventMarketPriceTick,
  unknown
> = z.object({
  data: z.pipe(
    z.pipe(
      z.unknown(),
      z.transform((v, ctx) => {
        if (typeof v !== "string") return v;
        try {
          return JSON.parse(v);
        } catch (err) {
          ctx.issues.push({
            input: v,
            code: "custom",
            message: `malformed json: ${err}`,
          });
          return z.NEVER;
        }
      }),
    ),
    components.EventMarketPriceTickData$inboundSchema,
  ),
  event: z.literal("market-price-tick"),
  id: z.optional(z.string()),
  retry: z.optional(z.int()),
});

export function eventMarketPriceTickFromJSON(
  jsonString: string,
): SafeParseResult<EventMarketPriceTick, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EventMarketPriceTick$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EventMarketPriceTick' from JSON`,
  );
}

/** @internal */
export const ServerSentEventsEventHeartbeat$inboundSchema: z.ZodMiniType<
  ServerSentEventsEventHeartbeat,
  unknown
> = z.object({
  data: z.pipe(
    z.pipe(
      z.unknown(),
      z.transform((v, ctx) => {
        if (typeof v !== "string") return v;
        try {
          return JSON.parse(v);
        } catch (err) {
          ctx.issues.push({
            input: v,
            code: "custom",
            message: `malformed json: ${err}`,
          });
          return z.NEVER;
        }
      }),
    ),
    components.PricingHeartbeat$inboundSchema,
  ),
  event: z.literal("heartbeat"),
  id: z.optional(z.string()),
  retry: z.optional(z.int()),
});

export function serverSentEventsEventHeartbeatFromJSON(
  jsonString: string,
): SafeParseResult<ServerSentEventsEventHeartbeat, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServerSentEventsEventHeartbeat$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServerSentEventsEventHeartbeat' from JSON`,
  );
}

/** @internal */
export const BadgePricingSubscribeServerSentEvents$inboundSchema: z.ZodMiniType<
  BadgePricingSubscribeServerSentEvents,
  unknown
> = z.union([
  z.lazy(() => ServerSentEventsEventHeartbeat$inboundSchema),
  z.lazy(() => EventMarketPriceTick$inboundSchema),
]);

export function badgePricingSubscribeServerSentEventsFromJSON(
  jsonString: string,
): SafeParseResult<BadgePricingSubscribeServerSentEvents, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      BadgePricingSubscribeServerSentEvents$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BadgePricingSubscribeServerSentEvents' from JSON`,
  );
}

/** @internal */
export const BadgePricingSubscribeResponse$inboundSchema: z.ZodMiniType<
  BadgePricingSubscribeResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    "Server Sent Events": z.optional(
      z.pipe(
        z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
        z.transform(stream => {
          return new EventStream(stream, rawEvent => {
            return {
              done: false,
              value: z.union([
                z.lazy(() => ServerSentEventsEventHeartbeat$inboundSchema),
                z.lazy(() => EventMarketPriceTick$inboundSchema),
              ]).parse(rawEvent),
            };
          });
        }),
      ),
    ),
    ErrorModel: z.optional(components.ErrorModel$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "Server Sent Events": "serverSentEvents",
      "ErrorModel": "errorModel",
    });
  }),
);

export function badgePricingSubscribeResponseFromJSON(
  jsonString: string,
): SafeParseResult<BadgePricingSubscribeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BadgePricingSubscribeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BadgePricingSubscribeResponse' from JSON`,
  );
}
