/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { EventStream } from "../../lib/event-streams.js";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type EventMarketPriceTick = {
  data: components.EventMarketPriceTickData;
  /**
   * The event name.
   */
  event: "market-price-tick";
  /**
   * The event ID.
   */
  id?: string | undefined;
  /**
   * The retry time in milliseconds.
   */
  retry?: number | undefined;
};

export type EventHeartbeat = {
  data: components.PricingHeartbeat;
  /**
   * The event name.
   */
  event: "heartbeat";
  /**
   * The event ID.
   */
  id?: string | undefined;
  /**
   * The retry time in milliseconds.
   */
  retry?: number | undefined;
};

/**
 * Each oneOf object in the array represents one possible Server Sent Events (SSE) message, serialized as UTF-8 text according to the SSE specification.
 */
export type BadgePricingSubscribeServerSentEvents =
  | EventHeartbeat
  | EventMarketPriceTick;

export type BadgePricingSubscribeResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  serverSentEvents?:
    | EventStream<EventHeartbeat | EventMarketPriceTick>
    | undefined;
  /**
   * Error
   */
  errorModel?: components.ErrorModel | undefined;
};

/** @internal */
export const EventMarketPriceTick$inboundSchema: z.ZodType<
  EventMarketPriceTick,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.string().transform((v, ctx) => {
    try {
      return JSON.parse(v);
    } catch (err) {
      ctx.addIssue({ code: "custom", message: `malformed json: ${err}` });
      return z.NEVER;
    }
  }).pipe(components.EventMarketPriceTickData$inboundSchema),
  event: z.literal("market-price-tick"),
  id: z.string().optional(),
  retry: z.number().int().optional(),
});

export function eventMarketPriceTickFromJSON(
  jsonString: string,
): SafeParseResult<EventMarketPriceTick, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EventMarketPriceTick$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EventMarketPriceTick' from JSON`,
  );
}

/** @internal */
export const EventHeartbeat$inboundSchema: z.ZodType<
  EventHeartbeat,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.string().transform((v, ctx) => {
    try {
      return JSON.parse(v);
    } catch (err) {
      ctx.addIssue({ code: "custom", message: `malformed json: ${err}` });
      return z.NEVER;
    }
  }).pipe(components.PricingHeartbeat$inboundSchema),
  event: z.literal("heartbeat"),
  id: z.string().optional(),
  retry: z.number().int().optional(),
});

export function eventHeartbeatFromJSON(
  jsonString: string,
): SafeParseResult<EventHeartbeat, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EventHeartbeat$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EventHeartbeat' from JSON`,
  );
}

/** @internal */
export const BadgePricingSubscribeServerSentEvents$inboundSchema: z.ZodType<
  BadgePricingSubscribeServerSentEvents,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => EventHeartbeat$inboundSchema),
  z.lazy(() => EventMarketPriceTick$inboundSchema),
]);

export function badgePricingSubscribeServerSentEventsFromJSON(
  jsonString: string,
): SafeParseResult<BadgePricingSubscribeServerSentEvents, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      BadgePricingSubscribeServerSentEvents$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BadgePricingSubscribeServerSentEvents' from JSON`,
  );
}

/** @internal */
export const BadgePricingSubscribeResponse$inboundSchema: z.ZodType<
  BadgePricingSubscribeResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  "Server Sent Events": z.instanceof(ReadableStream<Uint8Array>)
    .transform(stream => {
      return new EventStream(stream, rawEvent => {
        return {
          done: false,
          value: z.union([
            z.lazy(() => EventHeartbeat$inboundSchema),
            z.lazy(() => EventMarketPriceTick$inboundSchema),
          ]).parse(rawEvent),
        };
      });
    }).optional(),
  ErrorModel: components.ErrorModel$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "Server Sent Events": "serverSentEvents",
    "ErrorModel": "errorModel",
  });
});

export function badgePricingSubscribeResponseFromJSON(
  jsonString: string,
): SafeParseResult<BadgePricingSubscribeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BadgePricingSubscribeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BadgePricingSubscribeResponse' from JSON`,
  );
}
