/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DonateGetGoalResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1DonateGoal?: components.V1DonateGoal | undefined;
};

/** @internal */
export const DonateGetGoalResponse$inboundSchema: z.ZodType<
  DonateGetGoalResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V1DonateGoal: components.V1DonateGoal$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V1DonateGoal": "v1DonateGoal",
  });
});

export function donateGetGoalResponseFromJSON(
  jsonString: string,
): SafeParseResult<DonateGetGoalResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DonateGetGoalResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DonateGetGoalResponse' from JSON`,
  );
}
