/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ItemFindOwnersResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  findOwnersResponseBody?: components.FindOwnersResponseBody | undefined;
};

/** @internal */
export const ItemFindOwnersResponse$inboundSchema: z.ZodType<
  ItemFindOwnersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  FindOwnersResponseBody: components.FindOwnersResponseBody$inboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "FindOwnersResponseBody": "findOwnersResponseBody",
  });
});

export function itemFindOwnersResponseFromJSON(
  jsonString: string,
): SafeParseResult<ItemFindOwnersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ItemFindOwnersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ItemFindOwnersResponse' from JSON`,
  );
}
