/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type KvDeleteResponse = {
  httpMeta: components.HTTPMetadata;
};

/** @internal */
export const KvDeleteResponse$inboundSchema: z.ZodMiniType<
  KvDeleteResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
    });
  }),
);

export function kvDeleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<KvDeleteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KvDeleteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KvDeleteResponse' from JSON`,
  );
}
