/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LeaderboardListBadgesResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1LeaderboardListBadgesResponseBody?:
    | components.V1LeaderboardListBadgesResponseBody
    | undefined;
};

/** @internal */
export const LeaderboardListBadgesResponse$inboundSchema: z.ZodMiniType<
  LeaderboardListBadgesResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    V1LeaderboardListBadgesResponseBody: z.optional(
      components.V1LeaderboardListBadgesResponseBody$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "V1LeaderboardListBadgesResponseBody":
        "v1LeaderboardListBadgesResponseBody",
    });
  }),
);

export function leaderboardListBadgesResponseFromJSON(
  jsonString: string,
): SafeParseResult<LeaderboardListBadgesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LeaderboardListBadgesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LeaderboardListBadgesResponse' from JSON`,
  );
}
