/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LeaderboardGetGroupsMetaResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1LeaderboardGetGroupsMetaResponseBody?:
    | components.V1LeaderboardGetGroupsMetaResponseBody
    | undefined;
};

/** @internal */
export const LeaderboardGetGroupsMetaResponse$inboundSchema: z.ZodType<
  LeaderboardGetGroupsMetaResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V1LeaderboardGetGroupsMetaResponseBody: components
    .V1LeaderboardGetGroupsMetaResponseBody$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V1LeaderboardGetGroupsMetaResponseBody":
      "v1LeaderboardGetGroupsMetaResponseBody",
  });
});

export function leaderboardGetGroupsMetaResponseFromJSON(
  jsonString: string,
): SafeParseResult<LeaderboardGetGroupsMetaResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LeaderboardGetGroupsMetaResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LeaderboardGetGroupsMetaResponse' from JSON`,
  );
}
