/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostV1AccountDeleteDeveloperAppResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1AccountDeleteDeveloperAppResponseBody?:
    | components.V1AccountDeleteDeveloperAppResponseBody
    | undefined;
};

/** @internal */
export const PostV1AccountDeleteDeveloperAppResponse$inboundSchema: z.ZodType<
  PostV1AccountDeleteDeveloperAppResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V1AccountDeleteDeveloperAppResponseBody: components
    .V1AccountDeleteDeveloperAppResponseBody$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V1AccountDeleteDeveloperAppResponseBody":
      "v1AccountDeleteDeveloperAppResponseBody",
  });
});

/** @internal */
export type PostV1AccountDeleteDeveloperAppResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  V1AccountDeleteDeveloperAppResponseBody?:
    | components.V1AccountDeleteDeveloperAppResponseBody$Outbound
    | undefined;
};

/** @internal */
export const PostV1AccountDeleteDeveloperAppResponse$outboundSchema: z.ZodType<
  PostV1AccountDeleteDeveloperAppResponse$Outbound,
  z.ZodTypeDef,
  PostV1AccountDeleteDeveloperAppResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  v1AccountDeleteDeveloperAppResponseBody: components
    .V1AccountDeleteDeveloperAppResponseBody$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    v1AccountDeleteDeveloperAppResponseBody:
      "V1AccountDeleteDeveloperAppResponseBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV1AccountDeleteDeveloperAppResponse$ {
  /** @deprecated use `PostV1AccountDeleteDeveloperAppResponse$inboundSchema` instead. */
  export const inboundSchema =
    PostV1AccountDeleteDeveloperAppResponse$inboundSchema;
  /** @deprecated use `PostV1AccountDeleteDeveloperAppResponse$outboundSchema` instead. */
  export const outboundSchema =
    PostV1AccountDeleteDeveloperAppResponse$outboundSchema;
  /** @deprecated use `PostV1AccountDeleteDeveloperAppResponse$Outbound` instead. */
  export type Outbound = PostV1AccountDeleteDeveloperAppResponse$Outbound;
}

export function postV1AccountDeleteDeveloperAppResponseToJSON(
  postV1AccountDeleteDeveloperAppResponse:
    PostV1AccountDeleteDeveloperAppResponse,
): string {
  return JSON.stringify(
    PostV1AccountDeleteDeveloperAppResponse$outboundSchema.parse(
      postV1AccountDeleteDeveloperAppResponse,
    ),
  );
}

export function postV1AccountDeleteDeveloperAppResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PostV1AccountDeleteDeveloperAppResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1AccountDeleteDeveloperAppResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostV1AccountDeleteDeveloperAppResponse' from JSON`,
  );
}
