/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostV1AppListBadgesResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1AppListBadgesResponseBody?:
    | components.V1AppListBadgesResponseBody
    | undefined;
};

/** @internal */
export const PostV1AppListBadgesResponse$inboundSchema: z.ZodType<
  PostV1AppListBadgesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V1AppListBadgesResponseBody: components
    .V1AppListBadgesResponseBody$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V1AppListBadgesResponseBody": "v1AppListBadgesResponseBody",
  });
});

/** @internal */
export type PostV1AppListBadgesResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  V1AppListBadgesResponseBody?:
    | components.V1AppListBadgesResponseBody$Outbound
    | undefined;
};

/** @internal */
export const PostV1AppListBadgesResponse$outboundSchema: z.ZodType<
  PostV1AppListBadgesResponse$Outbound,
  z.ZodTypeDef,
  PostV1AppListBadgesResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  v1AppListBadgesResponseBody: components
    .V1AppListBadgesResponseBody$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    v1AppListBadgesResponseBody: "V1AppListBadgesResponseBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV1AppListBadgesResponse$ {
  /** @deprecated use `PostV1AppListBadgesResponse$inboundSchema` instead. */
  export const inboundSchema = PostV1AppListBadgesResponse$inboundSchema;
  /** @deprecated use `PostV1AppListBadgesResponse$outboundSchema` instead. */
  export const outboundSchema = PostV1AppListBadgesResponse$outboundSchema;
  /** @deprecated use `PostV1AppListBadgesResponse$Outbound` instead. */
  export type Outbound = PostV1AppListBadgesResponse$Outbound;
}

export function postV1AppListBadgesResponseToJSON(
  postV1AppListBadgesResponse: PostV1AppListBadgesResponse,
): string {
  return JSON.stringify(
    PostV1AppListBadgesResponse$outboundSchema.parse(
      postV1AppListBadgesResponse,
    ),
  );
}

export function postV1AppListBadgesResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1AppListBadgesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV1AppListBadgesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1AppListBadgesResponse' from JSON`,
  );
}
