/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostV1AccountListOwnedBadgesResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1AccountBadgeOwnedBadgesResponseBody?:
    | components.V1AccountBadgeOwnedBadgesResponseBody
    | undefined;
};

/** @internal */
export const PostV1AccountListOwnedBadgesResponse$inboundSchema: z.ZodType<
  PostV1AccountListOwnedBadgesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V1AccountBadgeOwnedBadgesResponseBody: components
    .V1AccountBadgeOwnedBadgesResponseBody$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V1AccountBadgeOwnedBadgesResponseBody":
      "v1AccountBadgeOwnedBadgesResponseBody",
  });
});

/** @internal */
export type PostV1AccountListOwnedBadgesResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  V1AccountBadgeOwnedBadgesResponseBody?:
    | components.V1AccountBadgeOwnedBadgesResponseBody$Outbound
    | undefined;
};

/** @internal */
export const PostV1AccountListOwnedBadgesResponse$outboundSchema: z.ZodType<
  PostV1AccountListOwnedBadgesResponse$Outbound,
  z.ZodTypeDef,
  PostV1AccountListOwnedBadgesResponse
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  v1AccountBadgeOwnedBadgesResponseBody: components
    .V1AccountBadgeOwnedBadgesResponseBody$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    v1AccountBadgeOwnedBadgesResponseBody:
      "V1AccountBadgeOwnedBadgesResponseBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV1AccountListOwnedBadgesResponse$ {
  /** @deprecated use `PostV1AccountListOwnedBadgesResponse$inboundSchema` instead. */
  export const inboundSchema =
    PostV1AccountListOwnedBadgesResponse$inboundSchema;
  /** @deprecated use `PostV1AccountListOwnedBadgesResponse$outboundSchema` instead. */
  export const outboundSchema =
    PostV1AccountListOwnedBadgesResponse$outboundSchema;
  /** @deprecated use `PostV1AccountListOwnedBadgesResponse$Outbound` instead. */
  export type Outbound = PostV1AccountListOwnedBadgesResponse$Outbound;
}

export function postV1AccountListOwnedBadgesResponseToJSON(
  postV1AccountListOwnedBadgesResponse: PostV1AccountListOwnedBadgesResponse,
): string {
  return JSON.stringify(
    PostV1AccountListOwnedBadgesResponse$outboundSchema.parse(
      postV1AccountListOwnedBadgesResponse,
    ),
  );
}

export function postV1AccountListOwnedBadgesResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1AccountListOwnedBadgesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1AccountListOwnedBadgesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1AccountListOwnedBadgesResponse' from JSON`,
  );
}
