/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostV1LeaderboardGetAccountLeaderboardResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1LeaderboardGetAccountLeaderboardResponseBody?:
    | components.V1LeaderboardGetAccountLeaderboardResponseBody
    | undefined;
};

/** @internal */
export const PostV1LeaderboardGetAccountLeaderboardResponse$inboundSchema:
  z.ZodType<
    PostV1LeaderboardGetAccountLeaderboardResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    V1LeaderboardGetAccountLeaderboardResponseBody: components
      .V1LeaderboardGetAccountLeaderboardResponseBody$inboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "V1LeaderboardGetAccountLeaderboardResponseBody":
        "v1LeaderboardGetAccountLeaderboardResponseBody",
    });
  });

/** @internal */
export type PostV1LeaderboardGetAccountLeaderboardResponse$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  V1LeaderboardGetAccountLeaderboardResponseBody?:
    | components.V1LeaderboardGetAccountLeaderboardResponseBody$Outbound
    | undefined;
};

/** @internal */
export const PostV1LeaderboardGetAccountLeaderboardResponse$outboundSchema:
  z.ZodType<
    PostV1LeaderboardGetAccountLeaderboardResponse$Outbound,
    z.ZodTypeDef,
    PostV1LeaderboardGetAccountLeaderboardResponse
  > = z.object({
    httpMeta: components.HTTPMetadata$outboundSchema,
    v1LeaderboardGetAccountLeaderboardResponseBody: components
      .V1LeaderboardGetAccountLeaderboardResponseBody$outboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      httpMeta: "HttpMeta",
      v1LeaderboardGetAccountLeaderboardResponseBody:
        "V1LeaderboardGetAccountLeaderboardResponseBody",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV1LeaderboardGetAccountLeaderboardResponse$ {
  /** @deprecated use `PostV1LeaderboardGetAccountLeaderboardResponse$inboundSchema` instead. */
  export const inboundSchema =
    PostV1LeaderboardGetAccountLeaderboardResponse$inboundSchema;
  /** @deprecated use `PostV1LeaderboardGetAccountLeaderboardResponse$outboundSchema` instead. */
  export const outboundSchema =
    PostV1LeaderboardGetAccountLeaderboardResponse$outboundSchema;
  /** @deprecated use `PostV1LeaderboardGetAccountLeaderboardResponse$Outbound` instead. */
  export type Outbound =
    PostV1LeaderboardGetAccountLeaderboardResponse$Outbound;
}

export function postV1LeaderboardGetAccountLeaderboardResponseToJSON(
  postV1LeaderboardGetAccountLeaderboardResponse:
    PostV1LeaderboardGetAccountLeaderboardResponse,
): string {
  return JSON.stringify(
    PostV1LeaderboardGetAccountLeaderboardResponse$outboundSchema.parse(
      postV1LeaderboardGetAccountLeaderboardResponse,
    ),
  );
}

export function postV1LeaderboardGetAccountLeaderboardResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PostV1LeaderboardGetAccountLeaderboardResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1LeaderboardGetAccountLeaderboardResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostV1LeaderboardGetAccountLeaderboardResponse' from JSON`,
  );
}
