/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostV1LeaderboardListBadges33Response = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  v1LeaderboardListBadgesResponseBody?:
    | components.V1LeaderboardListBadgesResponseBody
    | undefined;
};

/** @internal */
export const PostV1LeaderboardListBadges33Response$inboundSchema: z.ZodType<
  PostV1LeaderboardListBadges33Response,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  V1LeaderboardListBadgesResponseBody: components
    .V1LeaderboardListBadgesResponseBody$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "V1LeaderboardListBadgesResponseBody":
      "v1LeaderboardListBadgesResponseBody",
  });
});

/** @internal */
export type PostV1LeaderboardListBadges33Response$Outbound = {
  HttpMeta: components.HTTPMetadata$Outbound;
  V1LeaderboardListBadgesResponseBody?:
    | components.V1LeaderboardListBadgesResponseBody$Outbound
    | undefined;
};

/** @internal */
export const PostV1LeaderboardListBadges33Response$outboundSchema: z.ZodType<
  PostV1LeaderboardListBadges33Response$Outbound,
  z.ZodTypeDef,
  PostV1LeaderboardListBadges33Response
> = z.object({
  httpMeta: components.HTTPMetadata$outboundSchema,
  v1LeaderboardListBadgesResponseBody: components
    .V1LeaderboardListBadgesResponseBody$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    httpMeta: "HttpMeta",
    v1LeaderboardListBadgesResponseBody: "V1LeaderboardListBadgesResponseBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV1LeaderboardListBadges33Response$ {
  /** @deprecated use `PostV1LeaderboardListBadges33Response$inboundSchema` instead. */
  export const inboundSchema =
    PostV1LeaderboardListBadges33Response$inboundSchema;
  /** @deprecated use `PostV1LeaderboardListBadges33Response$outboundSchema` instead. */
  export const outboundSchema =
    PostV1LeaderboardListBadges33Response$outboundSchema;
  /** @deprecated use `PostV1LeaderboardListBadges33Response$Outbound` instead. */
  export type Outbound = PostV1LeaderboardListBadges33Response$Outbound;
}

export function postV1LeaderboardListBadges33ResponseToJSON(
  postV1LeaderboardListBadges33Response: PostV1LeaderboardListBadges33Response,
): string {
  return JSON.stringify(
    PostV1LeaderboardListBadges33Response$outboundSchema.parse(
      postV1LeaderboardListBadges33Response,
    ),
  );
}

export function postV1LeaderboardListBadges33ResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV1LeaderboardListBadges33Response, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostV1LeaderboardListBadges33Response$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV1LeaderboardListBadges33Response' from JSON`,
  );
}
