/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type StaffListStaffResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  leaderboardAccounts?:
    | Array<components.LeaderboardAccount | null>
    | null
    | undefined;
  headers: { [k: string]: Array<string> };
};

/** @internal */
export const StaffListStaffResponse$inboundSchema: z.ZodType<
  StaffListStaffResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  LeaderboardAccounts: z.nullable(
    z.array(z.nullable(components.LeaderboardAccount$inboundSchema)),
  ).optional(),
  Headers: z.record(z.array(z.string())).default({}),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "LeaderboardAccounts": "leaderboardAccounts",
    "Headers": "headers",
  });
});

export function staffListStaffResponseFromJSON(
  jsonString: string,
): SafeParseResult<StaffListStaffResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StaffListStaffResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StaffListStaffResponse' from JSON`,
  );
}
