/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type TrackEventRequest = {
  xForwardedFor?: string | undefined;
  userAgent?: string | undefined;
  xVisitorId?: string | undefined;
  analyticsTrackEventRequestBody: components.AnalyticsTrackEventRequestBody;
};

export type TrackEventResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  analyticsTrackEventResponseBody?:
    | components.AnalyticsTrackEventResponseBody
    | undefined;
};

/** @internal */
export type TrackEventRequest$Outbound = {
  "X-Forwarded-For"?: string | undefined;
  "User-Agent"?: string | undefined;
  "X-Visitor-Id"?: string | undefined;
  AnalyticsTrackEventRequestBody:
    components.AnalyticsTrackEventRequestBody$Outbound;
};

/** @internal */
export const TrackEventRequest$outboundSchema: z.ZodMiniType<
  TrackEventRequest$Outbound,
  TrackEventRequest
> = z.pipe(
  z.object({
    xForwardedFor: z.optional(z.string()),
    userAgent: z.optional(z.string()),
    xVisitorId: z.optional(z.string()),
    analyticsTrackEventRequestBody:
      components.AnalyticsTrackEventRequestBody$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      xForwardedFor: "X-Forwarded-For",
      userAgent: "User-Agent",
      xVisitorId: "X-Visitor-Id",
      analyticsTrackEventRequestBody: "AnalyticsTrackEventRequestBody",
    });
  }),
);

export function trackEventRequestToJSON(
  trackEventRequest: TrackEventRequest,
): string {
  return JSON.stringify(
    TrackEventRequest$outboundSchema.parse(trackEventRequest),
  );
}

/** @internal */
export const TrackEventResponse$inboundSchema: z.ZodMiniType<
  TrackEventResponse,
  unknown
> = z.pipe(
  z.object({
    HttpMeta: components.HTTPMetadata$inboundSchema,
    AnalyticsTrackEventResponseBody: z.optional(
      components.AnalyticsTrackEventResponseBody$inboundSchema,
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "HttpMeta": "httpMeta",
      "AnalyticsTrackEventResponseBody": "analyticsTrackEventResponseBody",
    });
  }),
);

export function trackEventResponseFromJSON(
  jsonString: string,
): SafeParseResult<TrackEventResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TrackEventResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TrackEventResponse' from JSON`,
  );
}
