/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type TradingItemSearchItemsRequest = {
  xForwardedFor?: string | undefined;
  userAgent?: string | undefined;
  xVisitorId?: string | undefined;
  tradingItemSearchItemsRequestBody:
    components.TradingItemSearchItemsRequestBody;
};

export type TradingItemSearchItemsResponse = {
  httpMeta: components.HTTPMetadata;
  /**
   * OK
   */
  tradingItemSearchItemsResponseBody?:
    | components.TradingItemSearchItemsResponseBody
    | undefined;
};

/** @internal */
export type TradingItemSearchItemsRequest$Outbound = {
  "X-Forwarded-For"?: string | undefined;
  "User-Agent"?: string | undefined;
  "X-Visitor-Id"?: string | undefined;
  TradingItemSearchItemsRequestBody:
    components.TradingItemSearchItemsRequestBody$Outbound;
};

/** @internal */
export const TradingItemSearchItemsRequest$outboundSchema: z.ZodType<
  TradingItemSearchItemsRequest$Outbound,
  z.ZodTypeDef,
  TradingItemSearchItemsRequest
> = z.object({
  xForwardedFor: z.string().optional(),
  userAgent: z.string().optional(),
  xVisitorId: z.string().optional(),
  tradingItemSearchItemsRequestBody:
    components.TradingItemSearchItemsRequestBody$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    xForwardedFor: "X-Forwarded-For",
    userAgent: "User-Agent",
    xVisitorId: "X-Visitor-Id",
    tradingItemSearchItemsRequestBody: "TradingItemSearchItemsRequestBody",
  });
});

export function tradingItemSearchItemsRequestToJSON(
  tradingItemSearchItemsRequest: TradingItemSearchItemsRequest,
): string {
  return JSON.stringify(
    TradingItemSearchItemsRequest$outboundSchema.parse(
      tradingItemSearchItemsRequest,
    ),
  );
}

/** @internal */
export const TradingItemSearchItemsResponse$inboundSchema: z.ZodType<
  TradingItemSearchItemsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  HttpMeta: components.HTTPMetadata$inboundSchema,
  TradingItemSearchItemsResponseBody: components
    .TradingItemSearchItemsResponseBody$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "HttpMeta": "httpMeta",
    "TradingItemSearchItemsResponseBody": "tradingItemSearchItemsResponseBody",
  });
});

export function tradingItemSearchItemsResponseFromJSON(
  jsonString: string,
): SafeParseResult<TradingItemSearchItemsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TradingItemSearchItemsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TradingItemSearchItemsResponse' from JSON`,
  );
}
