/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";
import {
  AccountBoolFilter,
  AccountBoolFilter$Outbound,
  AccountBoolFilter$outboundSchema,
} from "./accountboolfilter.js";
import {
  AccountRangeFilter,
  AccountRangeFilter$Outbound,
  AccountRangeFilter$outboundSchema,
} from "./accountrangefilter.js";
import {
  AccountStringArrayFilter,
  AccountStringArrayFilter$Outbound,
  AccountStringArrayFilter$outboundSchema,
} from "./accountstringarrayfilter.js";
import {
  AccountStringFilter,
  AccountStringFilter$Outbound,
  AccountStringFilter$outboundSchema,
} from "./accountstringfilter.js";

export const Banned = {
  Excluded: "excluded",
  Only: "only",
} as const;
export type Banned = ClosedEnum<typeof Banned>;

export type AccountFilter = {
  accountId?: AccountRangeFilter | undefined;
  apps?: AccountRangeFilter | undefined;
  awardsGiven?: AccountRangeFilter | undefined;
  awardsReceived?: AccountRangeFilter | undefined;
  banned?: Banned | undefined;
  city?: AccountStringFilter | undefined;
  communityBanned?: AccountBoolFilter | undefined;
  country?: AccountStringFilter | undefined;
  createdAt?: AccountRangeFilter | undefined;
  donations?: AccountRangeFilter | undefined;
  foilBadges?: AccountRangeFilter | undefined;
  friends?: AccountRangeFilter | undefined;
  gameBans?: AccountRangeFilter | undefined;
  level?: AccountRangeFilter | undefined;
  normalBadges?: AccountRangeFilter | undefined;
  playtime?: AccountRangeFilter | undefined;
  pointsGiven?: AccountRangeFilter | undefined;
  pointsReceived?: AccountRangeFilter | undefined;
  privacy?: AccountStringFilter | undefined;
  region?: AccountStringFilter | undefined;
  roles?: AccountStringArrayFilter | undefined;
  state?: AccountStringFilter | undefined;
  steamSetsScore?: AccountRangeFilter | undefined;
  steamVanity?: AccountStringFilter | undefined;
  totalBadges?: AccountRangeFilter | undefined;
  tradeBanned?: AccountBoolFilter | undefined;
  vacBans?: AccountRangeFilter | undefined;
  vanity?: AccountStringFilter | undefined;
  xp?: AccountRangeFilter | undefined;
};

/** @internal */
export const Banned$outboundSchema: z.ZodNativeEnum<typeof Banned> = z
  .nativeEnum(Banned);

/** @internal */
export type AccountFilter$Outbound = {
  accountId?: AccountRangeFilter$Outbound | undefined;
  apps?: AccountRangeFilter$Outbound | undefined;
  awardsGiven?: AccountRangeFilter$Outbound | undefined;
  awardsReceived?: AccountRangeFilter$Outbound | undefined;
  banned?: string | undefined;
  city?: AccountStringFilter$Outbound | undefined;
  communityBanned?: AccountBoolFilter$Outbound | undefined;
  country?: AccountStringFilter$Outbound | undefined;
  createdAt?: AccountRangeFilter$Outbound | undefined;
  donations?: AccountRangeFilter$Outbound | undefined;
  foilBadges?: AccountRangeFilter$Outbound | undefined;
  friends?: AccountRangeFilter$Outbound | undefined;
  gameBans?: AccountRangeFilter$Outbound | undefined;
  level?: AccountRangeFilter$Outbound | undefined;
  normalBadges?: AccountRangeFilter$Outbound | undefined;
  playtime?: AccountRangeFilter$Outbound | undefined;
  pointsGiven?: AccountRangeFilter$Outbound | undefined;
  pointsReceived?: AccountRangeFilter$Outbound | undefined;
  privacy?: AccountStringFilter$Outbound | undefined;
  region?: AccountStringFilter$Outbound | undefined;
  roles?: AccountStringArrayFilter$Outbound | undefined;
  state?: AccountStringFilter$Outbound | undefined;
  steamSetsScore?: AccountRangeFilter$Outbound | undefined;
  steamVanity?: AccountStringFilter$Outbound | undefined;
  totalBadges?: AccountRangeFilter$Outbound | undefined;
  tradeBanned?: AccountBoolFilter$Outbound | undefined;
  vacBans?: AccountRangeFilter$Outbound | undefined;
  vanity?: AccountStringFilter$Outbound | undefined;
  xp?: AccountRangeFilter$Outbound | undefined;
};

/** @internal */
export const AccountFilter$outboundSchema: z.ZodType<
  AccountFilter$Outbound,
  z.ZodTypeDef,
  AccountFilter
> = z.object({
  accountId: AccountRangeFilter$outboundSchema.optional(),
  apps: AccountRangeFilter$outboundSchema.optional(),
  awardsGiven: AccountRangeFilter$outboundSchema.optional(),
  awardsReceived: AccountRangeFilter$outboundSchema.optional(),
  banned: Banned$outboundSchema.optional(),
  city: AccountStringFilter$outboundSchema.optional(),
  communityBanned: AccountBoolFilter$outboundSchema.optional(),
  country: AccountStringFilter$outboundSchema.optional(),
  createdAt: AccountRangeFilter$outboundSchema.optional(),
  donations: AccountRangeFilter$outboundSchema.optional(),
  foilBadges: AccountRangeFilter$outboundSchema.optional(),
  friends: AccountRangeFilter$outboundSchema.optional(),
  gameBans: AccountRangeFilter$outboundSchema.optional(),
  level: AccountRangeFilter$outboundSchema.optional(),
  normalBadges: AccountRangeFilter$outboundSchema.optional(),
  playtime: AccountRangeFilter$outboundSchema.optional(),
  pointsGiven: AccountRangeFilter$outboundSchema.optional(),
  pointsReceived: AccountRangeFilter$outboundSchema.optional(),
  privacy: AccountStringFilter$outboundSchema.optional(),
  region: AccountStringFilter$outboundSchema.optional(),
  roles: AccountStringArrayFilter$outboundSchema.optional(),
  state: AccountStringFilter$outboundSchema.optional(),
  steamSetsScore: AccountRangeFilter$outboundSchema.optional(),
  steamVanity: AccountStringFilter$outboundSchema.optional(),
  totalBadges: AccountRangeFilter$outboundSchema.optional(),
  tradeBanned: AccountBoolFilter$outboundSchema.optional(),
  vacBans: AccountRangeFilter$outboundSchema.optional(),
  vanity: AccountStringFilter$outboundSchema.optional(),
  xp: AccountRangeFilter$outboundSchema.optional(),
});

export function accountFilterToJSON(accountFilter: AccountFilter): string {
  return JSON.stringify(AccountFilter$outboundSchema.parse(accountFilter));
}
