/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AccountViewStats = {
  /**
   * A URL to the JSON Schema for this object.
   */
  dollarSchema?: string | undefined;
  /**
   * Total profile loads in the last 24 hours
   */
  total24h: number;
  /**
   * Total profile loads in the last 30 days
   */
  total30d: number;
  /**
   * Total profile loads in the last 7 days
   */
  total7d: number;
  /**
   * Distinct viewers in the last 24 hours
   */
  unique24h: number;
  /**
   * Distinct viewers in the last 30 days
   */
  unique30d: number;
  /**
   * Distinct viewers in the last 7 days
   */
  unique7d: number;
};

/** @internal */
export const AccountViewStats$inboundSchema: z.ZodType<
  AccountViewStats,
  z.ZodTypeDef,
  unknown
> = z.object({
  $schema: z.string().optional(),
  total24h: z.number().int(),
  total30d: z.number().int(),
  total7d: z.number().int(),
  unique24h: z.number().int(),
  unique30d: z.number().int(),
  unique7d: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "$schema": "dollarSchema",
  });
});

export function accountViewStatsFromJSON(
  jsonString: string,
): SafeParseResult<AccountViewStats, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountViewStats$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountViewStats' from JSON`,
  );
}
