/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  IDSearch,
  IDSearch$Outbound,
  IDSearch$outboundSchema,
} from "./idsearch.js";
import {
  VanitySearch,
  VanitySearch$Outbound,
  VanitySearch$outboundSchema,
} from "./vanitysearch.js";

export type AccountSearch = {
  id?: IDSearch | undefined;
  vanity?: VanitySearch | undefined;
};

/** @internal */
export type AccountSearch$Outbound = {
  id?: IDSearch$Outbound | undefined;
  vanity?: VanitySearch$Outbound | undefined;
};

/** @internal */
export const AccountSearch$outboundSchema: z.ZodType<
  AccountSearch$Outbound,
  z.ZodTypeDef,
  AccountSearch
> = z.object({
  id: IDSearch$outboundSchema.optional(),
  vanity: VanitySearch$outboundSchema.optional(),
});

export function accountSearchToJSON(accountSearch: AccountSearch): string {
  return JSON.stringify(AccountSearch$outboundSchema.parse(accountSearch));
}
