/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AccountOptOutResponseBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  dollarSchema?: string | undefined;
  /**
   * Whether the account is hidden site-wide after this call
   */
  hidden: boolean;
  /**
   * Always true on success
   */
  optedOut: boolean;
  /**
   * How many live sessions this call killed
   */
  sessionsRevoked: number;
};

/** @internal */
export const AccountOptOutResponseBody$inboundSchema: z.ZodMiniType<
  AccountOptOutResponseBody,
  unknown
> = z.pipe(
  z.object({
    $schema: z.optional(z.string()),
    hidden: z.boolean(),
    optedOut: z.boolean(),
    sessionsRevoked: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "$schema": "dollarSchema",
    });
  }),
);

export function accountOptOutResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<AccountOptOutResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountOptOutResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountOptOutResponseBody' from JSON`,
  );
}
