/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Account, Account$inboundSchema } from "./account.js";

export type AccountSearchAccountsResponseBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  dollarSchema?: string | undefined;
  accounts: Array<Account> | null;
  /**
   * Number of accounts returned in this page.
   */
  results: number;
};

/** @internal */
export const AccountSearchAccountsResponseBody$inboundSchema: z.ZodType<
  AccountSearchAccountsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  $schema: z.string().optional(),
  accounts: z.nullable(z.array(Account$inboundSchema)),
  results: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "$schema": "dollarSchema",
  });
});

export function accountSearchAccountsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<AccountSearchAccountsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountSearchAccountsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountSearchAccountsResponseBody' from JSON`,
  );
}
