/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AccountUpdateError,
  AccountUpdateError$inboundSchema,
} from "./accountupdateerror.js";
import {
  AccountUpdateStep,
  AccountUpdateStep$inboundSchema,
} from "./accountupdatestep.js";

export type AccountUpdateProgress = {
  accountId: number;
  currentStep: string;
  error?: AccountUpdateError | undefined;
  finishedAt?: Date | undefined;
  percent: number;
  queuePosition?: number | undefined;
  queuedAt?: Date | undefined;
  runId: string;
  startedAt?: Date | undefined;
  status: string;
  steps: Array<AccountUpdateStep> | null;
  updatedAt: Date;
};

/** @internal */
export const AccountUpdateProgress$inboundSchema: z.ZodMiniType<
  AccountUpdateProgress,
  unknown
> = z.object({
  accountId: z.int(),
  currentStep: z.string(),
  error: z.optional(AccountUpdateError$inboundSchema),
  finishedAt: z.optional(
    z.pipe(z.iso.datetime({ offset: true }), z.transform(v => new Date(v))),
  ),
  percent: z.int(),
  queuePosition: z.optional(z.int()),
  queuedAt: z.optional(
    z.pipe(z.iso.datetime({ offset: true }), z.transform(v => new Date(v))),
  ),
  runId: z.string(),
  startedAt: z.optional(
    z.pipe(z.iso.datetime({ offset: true }), z.transform(v => new Date(v))),
  ),
  status: z.string(),
  steps: z.nullable(z.array(AccountUpdateStep$inboundSchema)),
  updatedAt: z.pipe(
    z.iso.datetime({ offset: true }),
    z.transform(v => new Date(v)),
  ),
});

export function accountUpdateProgressFromJSON(
  jsonString: string,
): SafeParseResult<AccountUpdateProgress, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountUpdateProgress$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountUpdateProgress' from JSON`,
  );
}
