/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AccountArchiveNotificationsResponseBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  dollarSchema?: string | undefined;
};

/** @internal */
export const AccountArchiveNotificationsResponseBody$inboundSchema:
  z.ZodMiniType<AccountArchiveNotificationsResponseBody, unknown> = z.pipe(
    z.object({
      $schema: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "$schema": "dollarSchema",
      });
    }),
  );

export function accountArchiveNotificationsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  AccountArchiveNotificationsResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      AccountArchiveNotificationsResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'AccountArchiveNotificationsResponseBody' from JSON`,
  );
}
