/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type AccountListNotificationsRequestBody = {
  /**
   * List archived notifications instead of the inbox
   */
  archived?: boolean | undefined;
  /**
   * Cursor: the nextCursor of the page before. Leave it out for the first page
   */
  before?: number | undefined;
  /**
   * Notifications per page
   */
  limit?: number | undefined;
};

/** @internal */
export type AccountListNotificationsRequestBody$Outbound = {
  archived?: boolean | undefined;
  before?: number | undefined;
  limit: number;
};

/** @internal */
export const AccountListNotificationsRequestBody$outboundSchema: z.ZodMiniType<
  AccountListNotificationsRequestBody$Outbound,
  AccountListNotificationsRequestBody
> = z.object({
  archived: z.optional(z.boolean()),
  before: z.optional(z.int()),
  limit: z._default(z.int(), 20),
});

export function accountListNotificationsRequestBodyToJSON(
  accountListNotificationsRequestBody: AccountListNotificationsRequestBody,
): string {
  return JSON.stringify(
    AccountListNotificationsRequestBody$outboundSchema.parse(
      accountListNotificationsRequestBody,
    ),
  );
}
