/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AccountNotificationCardAcquired,
  AccountNotificationCardAcquired$inboundSchema,
} from "./accountnotificationcardacquired.js";
import {
  AccountNotificationConnectionBroken,
  AccountNotificationConnectionBroken$inboundSchema,
} from "./accountnotificationconnectionbroken.js";

export const AccountNotificationKind = {
  CardAcquired: "card_acquired",
  ConnectionBroken: "connection_broken",
} as const;
export type AccountNotificationKind = OpenEnum<typeof AccountNotificationKind>;

export type AccountNotification = {
  /**
   * When the account archived it, null in the inbox
   */
  archivedAt: Date | null;
  cardAcquired?: AccountNotificationCardAcquired | null | undefined;
  connectionBroken?: AccountNotificationConnectionBroken | null | undefined;
  createdAt: Date;
  id: number;
  kind: AccountNotificationKind;
  /**
   * When the account read it, null while unread
   */
  readAt: Date | null;
};

/** @internal */
export const AccountNotificationKind$inboundSchema: z.ZodMiniType<
  AccountNotificationKind,
  unknown
> = openEnums.inboundSchema(AccountNotificationKind);

/** @internal */
export const AccountNotification$inboundSchema: z.ZodMiniType<
  AccountNotification,
  unknown
> = z.object({
  archivedAt: z.nullable(
    z.pipe(z.iso.datetime({ offset: true }), z.transform(v => new Date(v))),
  ),
  cardAcquired: z.optional(
    z.nullable(AccountNotificationCardAcquired$inboundSchema),
  ),
  connectionBroken: z.optional(
    z.nullable(AccountNotificationConnectionBroken$inboundSchema),
  ),
  createdAt: z.pipe(
    z.iso.datetime({ offset: true }),
    z.transform(v => new Date(v)),
  ),
  id: z.int(),
  kind: AccountNotificationKind$inboundSchema,
  readAt: z.nullable(
    z.pipe(z.iso.datetime({ offset: true }), z.transform(v => new Date(v))),
  ),
});

export function accountNotificationFromJSON(
  jsonString: string,
): SafeParseResult<AccountNotification, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountNotification$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountNotification' from JSON`,
  );
}
