/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type AccountArchiveNotificationsRequestBody = {
  /**
   * false moves the given notifications back to the inbox
   */
  archived?: boolean | undefined;
  /**
   * The notifications to change. Leave it out to archive every inbox notification
   */
  ids?: Array<number> | null | undefined;
};

/** @internal */
export type AccountArchiveNotificationsRequestBody$Outbound = {
  archived: boolean;
  ids?: Array<number> | null | undefined;
};

/** @internal */
export const AccountArchiveNotificationsRequestBody$outboundSchema:
  z.ZodMiniType<
    AccountArchiveNotificationsRequestBody$Outbound,
    AccountArchiveNotificationsRequestBody
  > = z.object({
    archived: z._default(z.boolean(), true),
    ids: z.optional(z.nullable(z.array(z.int()))),
  });

export function accountArchiveNotificationsRequestBodyToJSON(
  accountArchiveNotificationsRequestBody:
    AccountArchiveNotificationsRequestBody,
): string {
  return JSON.stringify(
    AccountArchiveNotificationsRequestBody$outboundSchema.parse(
      accountArchiveNotificationsRequestBody,
    ),
  );
}
