/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AdminAccountResourceInherited = {
  /**
   * The highest-rated held role that grants the resource, or null when the code default applies
   */
  role: string | null;
  /**
   * That role's value, or null when the code default applies
   */
  value: string | null;
};

/** @internal */
export const AdminAccountResourceInherited$inboundSchema: z.ZodType<
  AdminAccountResourceInherited,
  z.ZodTypeDef,
  unknown
> = z.object({
  role: z.nullable(z.string()),
  value: z.nullable(z.string()),
});

export function adminAccountResourceInheritedFromJSON(
  jsonString: string,
): SafeParseResult<AdminAccountResourceInherited, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AdminAccountResourceInherited$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AdminAccountResourceInherited' from JSON`,
  );
}
