/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AnalyticsDomainEntry,
  AnalyticsDomainEntry$inboundSchema,
} from "./analyticsdomainentry.js";

export type AnalyticsListMetricsResponseBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  dollarSchema?: string | undefined;
  domains: Array<AnalyticsDomainEntry> | null;
};

/** @internal */
export const AnalyticsListMetricsResponseBody$inboundSchema: z.ZodType<
  AnalyticsListMetricsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  $schema: z.string().optional(),
  domains: z.nullable(z.array(AnalyticsDomainEntry$inboundSchema)),
}).transform((v) => {
  return remap$(v, {
    "$schema": "dollarSchema",
  });
});

export function analyticsListMetricsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<AnalyticsListMetricsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnalyticsListMetricsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnalyticsListMetricsResponseBody' from JSON`,
  );
}
