/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AnalyticsMetricEntry,
  AnalyticsMetricEntry$inboundSchema,
} from "./analyticsmetricentry.js";
import {
  AnalyticsScopeEntry,
  AnalyticsScopeEntry$inboundSchema,
} from "./analyticsscopeentry.js";

export type AnalyticsDomainEntry = {
  id: string;
  metrics: Array<AnalyticsMetricEntry> | null;
  scopes: Array<AnalyticsScopeEntry> | null;
};

/** @internal */
export const AnalyticsDomainEntry$inboundSchema: z.ZodType<
  AnalyticsDomainEntry,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  metrics: z.nullable(z.array(AnalyticsMetricEntry$inboundSchema)),
  scopes: z.nullable(z.array(AnalyticsScopeEntry$inboundSchema)),
});

export function analyticsDomainEntryFromJSON(
  jsonString: string,
): SafeParseResult<AnalyticsDomainEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnalyticsDomainEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnalyticsDomainEntry' from JSON`,
  );
}
