/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Event class. profile_view is normally emitted server-side; this lets the frontend top it up for client-only flows. search captures account/app searches that bypass the backend.
 */
export const AnalyticsTrackEventRequestBodyType = {
  ProfileView: "profile_view",
  Search: "search",
} as const;
/**
 * Event class. profile_view is normally emitted server-side; this lets the frontend top it up for client-only flows. search captures account/app searches that bypass the backend.
 */
export type AnalyticsTrackEventRequestBodyType = ClosedEnum<
  typeof AnalyticsTrackEventRequestBodyType
>;

export type AnalyticsTrackEventRequestBody = {
  /**
   * Per-type fields. profile_view: {accountId}. search: {source, query, resultCount}.
   */
  payload: { [k: string]: any };
  /**
   * Event class. profile_view is normally emitted server-side; this lets the frontend top it up for client-only flows. search captures account/app searches that bypass the backend.
   */
  type: AnalyticsTrackEventRequestBodyType;
};

/** @internal */
export const AnalyticsTrackEventRequestBodyType$outboundSchema: z.ZodNativeEnum<
  typeof AnalyticsTrackEventRequestBodyType
> = z.nativeEnum(AnalyticsTrackEventRequestBodyType);

/** @internal */
export type AnalyticsTrackEventRequestBody$Outbound = {
  payload: { [k: string]: any };
  type: string;
};

/** @internal */
export const AnalyticsTrackEventRequestBody$outboundSchema: z.ZodType<
  AnalyticsTrackEventRequestBody$Outbound,
  z.ZodTypeDef,
  AnalyticsTrackEventRequestBody
> = z.object({
  payload: z.record(z.any()),
  type: AnalyticsTrackEventRequestBodyType$outboundSchema,
});

export function analyticsTrackEventRequestBodyToJSON(
  analyticsTrackEventRequestBody: AnalyticsTrackEventRequestBody,
): string {
  return JSON.stringify(
    AnalyticsTrackEventRequestBody$outboundSchema.parse(
      analyticsTrackEventRequestBody,
    ),
  );
}
