/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AnalyticsTrackEventResponseBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  dollarSchema?: string | undefined;
  ok: boolean;
};

/** @internal */
export const AnalyticsTrackEventResponseBody$inboundSchema: z.ZodMiniType<
  AnalyticsTrackEventResponseBody,
  unknown
> = z.pipe(
  z.object({
    $schema: z.optional(z.string()),
    ok: z.boolean(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "$schema": "dollarSchema",
    });
  }),
);

export function analyticsTrackEventResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<AnalyticsTrackEventResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnalyticsTrackEventResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnalyticsTrackEventResponseBody' from JSON`,
  );
}
