/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Lookback window.
 */
export const AnalyticsGetTrendRequestBodyWindow = {
  Sevend: "7d",
  Thirtyd: "30d",
  Ninetyd: "90d",
} as const;
/**
 * Lookback window.
 */
export type AnalyticsGetTrendRequestBodyWindow = ClosedEnum<
  typeof AnalyticsGetTrendRequestBodyWindow
>;

export type AnalyticsGetTrendRequestBody = {
  /**
   * Analytics domain ID.
   */
  domain: string;
  /**
   * Metric ID within the domain.
   */
  metric: string;
  /**
   * Scope ID within the domain.
   */
  scope: string;
  /**
   * Country name/code or region name. Required for non-global scopes.
   */
  scopeValue?: string | undefined;
  /**
   * Lookback window.
   */
  window: AnalyticsGetTrendRequestBodyWindow;
};

/** @internal */
export const AnalyticsGetTrendRequestBodyWindow$outboundSchema: z.ZodNativeEnum<
  typeof AnalyticsGetTrendRequestBodyWindow
> = z.nativeEnum(AnalyticsGetTrendRequestBodyWindow);

/** @internal */
export type AnalyticsGetTrendRequestBody$Outbound = {
  domain: string;
  metric: string;
  scope: string;
  scope_value?: string | undefined;
  window: string;
};

/** @internal */
export const AnalyticsGetTrendRequestBody$outboundSchema: z.ZodType<
  AnalyticsGetTrendRequestBody$Outbound,
  z.ZodTypeDef,
  AnalyticsGetTrendRequestBody
> = z.object({
  domain: z.string(),
  metric: z.string(),
  scope: z.string(),
  scopeValue: z.string().optional(),
  window: AnalyticsGetTrendRequestBodyWindow$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    scopeValue: "scope_value",
  });
});

export function analyticsGetTrendRequestBodyToJSON(
  analyticsGetTrendRequestBody: AnalyticsGetTrendRequestBody,
): string {
  return JSON.stringify(
    AnalyticsGetTrendRequestBody$outboundSchema.parse(
      analyticsGetTrendRequestBody,
    ),
  );
}
