/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AnalyticsScopeEntry = {
  column: string;
  id: string;
  valueType: string;
};

/** @internal */
export const AnalyticsScopeEntry$inboundSchema: z.ZodType<
  AnalyticsScopeEntry,
  z.ZodTypeDef,
  unknown
> = z.object({
  column: z.string(),
  id: z.string(),
  value_type: z.string(),
}).transform((v) => {
  return remap$(v, {
    "value_type": "valueType",
  });
});

export function analyticsScopeEntryFromJSON(
  jsonString: string,
): SafeParseResult<AnalyticsScopeEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AnalyticsScopeEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AnalyticsScopeEntry' from JSON`,
  );
}
