/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AppListOwnersEntry,
  AppListOwnersEntry$inboundSchema,
} from "./applistownersentry.js";

export type AppListOwnersResponseBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  dollarSchema?: string | undefined;
  /**
   * Largest page size your donator tier allows
   */
  maxPageSize: number;
  /**
   * Pass as cursor to fetch the next page. Absent when there are no more owners.
   */
  nextCursor?: string | undefined;
  owners: Array<AppListOwnersEntry | null> | null;
  /**
   * Owners steamsets tracks for this app
   */
  trackedOwners: number;
};

/** @internal */
export const AppListOwnersResponseBody$inboundSchema: z.ZodType<
  AppListOwnersResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  $schema: z.string().optional(),
  maxPageSize: z.number().int(),
  nextCursor: z.string().optional(),
  owners: z.nullable(z.array(z.nullable(AppListOwnersEntry$inboundSchema))),
  trackedOwners: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "$schema": "dollarSchema",
  });
});

export function appListOwnersResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<AppListOwnersResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AppListOwnersResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AppListOwnersResponseBody' from JSON`,
  );
}
