/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type BadgeGetTagsTag = {
  id: string;
  name: string;
};

/** @internal */
export const BadgeGetTagsTag$inboundSchema: z.ZodMiniType<
  BadgeGetTagsTag,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
});

export function badgeGetTagsTagFromJSON(
  jsonString: string,
): SafeParseResult<BadgeGetTagsTag, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BadgeGetTagsTag$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BadgeGetTagsTag' from JSON`,
  );
}
