/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  AccountBoolFilter,
  AccountBoolFilter$Outbound,
  AccountBoolFilter$outboundSchema,
} from "./accountboolfilter.js";
import {
  AccountRangeFilter,
  AccountRangeFilter$Outbound,
  AccountRangeFilter$outboundSchema,
} from "./accountrangefilter.js";
import {
  AccountStringArrayFilter,
  AccountStringArrayFilter$Outbound,
  AccountStringArrayFilter$outboundSchema,
} from "./accountstringarrayfilter.js";
import {
  AccountStringFilter,
  AccountStringFilter$Outbound,
  AccountStringFilter$outboundSchema,
} from "./accountstringfilter.js";

export type BadgeFilter = {
  appId?: AccountRangeFilter | undefined;
  appName?: AccountStringFilter | undefined;
  colors?: AccountStringArrayFilter | undefined;
  designs?: AccountStringArrayFilter | undefined;
  isEvent?: AccountBoolFilter | undefined;
  isFoil?: AccountBoolFilter | undefined;
  isNmc?: AccountBoolFilter | undefined;
  isSale?: AccountBoolFilter | undefined;
  level?: AccountRangeFilter | undefined;
  scarcity?: AccountRangeFilter | undefined;
  steamId?: AccountRangeFilter | undefined;
  xp?: AccountRangeFilter | undefined;
};

/** @internal */
export type BadgeFilter$Outbound = {
  appId?: AccountRangeFilter$Outbound | undefined;
  appName?: AccountStringFilter$Outbound | undefined;
  colors?: AccountStringArrayFilter$Outbound | undefined;
  designs?: AccountStringArrayFilter$Outbound | undefined;
  isEvent?: AccountBoolFilter$Outbound | undefined;
  isFoil?: AccountBoolFilter$Outbound | undefined;
  isNmc?: AccountBoolFilter$Outbound | undefined;
  isSale?: AccountBoolFilter$Outbound | undefined;
  level?: AccountRangeFilter$Outbound | undefined;
  scarcity?: AccountRangeFilter$Outbound | undefined;
  steamId?: AccountRangeFilter$Outbound | undefined;
  xp?: AccountRangeFilter$Outbound | undefined;
};

/** @internal */
export const BadgeFilter$outboundSchema: z.ZodType<
  BadgeFilter$Outbound,
  z.ZodTypeDef,
  BadgeFilter
> = z.object({
  appId: AccountRangeFilter$outboundSchema.optional(),
  appName: AccountStringFilter$outboundSchema.optional(),
  colors: AccountStringArrayFilter$outboundSchema.optional(),
  designs: AccountStringArrayFilter$outboundSchema.optional(),
  isEvent: AccountBoolFilter$outboundSchema.optional(),
  isFoil: AccountBoolFilter$outboundSchema.optional(),
  isNmc: AccountBoolFilter$outboundSchema.optional(),
  isSale: AccountBoolFilter$outboundSchema.optional(),
  level: AccountRangeFilter$outboundSchema.optional(),
  scarcity: AccountRangeFilter$outboundSchema.optional(),
  steamId: AccountRangeFilter$outboundSchema.optional(),
  xp: AccountRangeFilter$outboundSchema.optional(),
});

export function badgeFilterToJSON(badgeFilter: BadgeFilter): string {
  return JSON.stringify(BadgeFilter$outboundSchema.parse(badgeFilter));
}
