/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The leaderboard of the best leaderboard
 */
export const Leaderboard = {
  Apps: "apps",
  AppPlaytime: "app_playtime",
  AppValidPlaytime: "app_valid_playtime",
  AwardsGiven: "awards_given",
  AwardsReceived: "awards_received",
  Bans: "bans",
  GameBans: "game_bans",
  VacBans: "vac_bans",
  Donations: "donations",
  FoilBadges: "foil_badges",
  NormalBadges: "normal_badges",
  Badges: "badges",
  Playtime: "playtime",
  ValidPlaytime: "valid_playtime",
  PointsGiven: "points_given",
  PointsReceived: "points_received",
  SteamSets: "steam_sets",
  Xp: "xp",
} as const;
/**
 * The leaderboard of the best leaderboard
 */
export type Leaderboard = ClosedEnum<typeof Leaderboard>;

export type BestLeaderboardRank = {
  /**
   * The leaderboard of the best leaderboard
   */
  leaderboard: Leaderboard;
  /**
   * The ranks in the leaderboard in csv global,regional,country,state,city
   */
  ranks: string;
};

/** @internal */
export const Leaderboard$inboundSchema: z.ZodNativeEnum<typeof Leaderboard> = z
  .nativeEnum(Leaderboard);

/** @internal */
export const BestLeaderboardRank$inboundSchema: z.ZodType<
  BestLeaderboardRank,
  z.ZodTypeDef,
  unknown
> = z.object({
  leaderboard: Leaderboard$inboundSchema,
  ranks: z.string(),
});

export function bestLeaderboardRankFromJSON(
  jsonString: string,
): SafeParseResult<BestLeaderboardRank, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BestLeaderboardRank$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BestLeaderboardRank' from JSON`,
  );
}
