/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CmsListItem = {
  docKey: string;
  parentUid?: string | undefined;
  payload?: any | undefined;
  sortOrder: number;
  uid: string;
};

/** @internal */
export const CmsListItem$inboundSchema: z.ZodType<
  CmsListItem,
  z.ZodTypeDef,
  unknown
> = z.object({
  doc_key: z.string(),
  parent_uid: z.string().optional(),
  payload: z.any().optional(),
  sort_order: z.number().int(),
  uid: z.string(),
}).transform((v) => {
  return remap$(v, {
    "doc_key": "docKey",
    "parent_uid": "parentUid",
    "sort_order": "sortOrder",
  });
});

export function cmsListItemFromJSON(
  jsonString: string,
): SafeParseResult<CmsListItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CmsListItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CmsListItem' from JSON`,
  );
}
