/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ColorTag = {
  group: string;
  groupOwner: boolean;
  hex: string | null;
  hsl: string;
  id: string;
  name: string;
};

/** @internal */
export const ColorTag$inboundSchema: z.ZodType<
  ColorTag,
  z.ZodTypeDef,
  unknown
> = z.object({
  group: z.string(),
  groupOwner: z.boolean(),
  hex: z.nullable(z.string()),
  hsl: z.string(),
  id: z.string(),
  name: z.string(),
});

export function colorTagFromJSON(
  jsonString: string,
): SafeParseResult<ColorTag, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ColorTag$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ColorTag' from JSON`,
  );
}
