/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The leaderboard of the best leaderboard
 */
export const CurrentLeaderboardRankLeaderboard = {
  Apps: "apps",
  AppPlaytime: "app_playtime",
  AppValidPlaytime: "app_valid_playtime",
  AwardsGiven: "awards_given",
  AwardsReceived: "awards_received",
  Bans: "bans",
  GameBans: "game_bans",
  VacBans: "vac_bans",
  Donations: "donations",
  FoilBadges: "foil_badges",
  NormalBadges: "normal_badges",
  Badges: "badges",
  Playtime: "playtime",
  ValidPlaytime: "valid_playtime",
  PointsGiven: "points_given",
  PointsReceived: "points_received",
  SteamSets: "steam_sets",
  Xp: "xp",
} as const;
/**
 * The leaderboard of the best leaderboard
 */
export type CurrentLeaderboardRankLeaderboard = OpenEnum<
  typeof CurrentLeaderboardRankLeaderboard
>;

export type CurrentLeaderboardRank = {
  /**
   * The leaderboard of the best leaderboard
   */
  leaderboard: CurrentLeaderboardRankLeaderboard;
  /**
   * The ranks in the leaderboard in csv global,regional,country,state,city
   */
  ranks: string;
  /**
   * The total ranked players per scope, same order as ranks: global,regional,country,state,city
   */
  totals: string;
};

/** @internal */
export const CurrentLeaderboardRankLeaderboard$inboundSchema: z.ZodType<
  CurrentLeaderboardRankLeaderboard,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(CurrentLeaderboardRankLeaderboard);

/** @internal */
export const CurrentLeaderboardRank$inboundSchema: z.ZodType<
  CurrentLeaderboardRank,
  z.ZodTypeDef,
  unknown
> = z.object({
  leaderboard: CurrentLeaderboardRankLeaderboard$inboundSchema,
  ranks: z.string(),
  totals: z.string(),
});

export function currentLeaderboardRankFromJSON(
  jsonString: string,
): SafeParseResult<CurrentLeaderboardRank, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CurrentLeaderboardRank$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CurrentLeaderboardRank' from JSON`,
  );
}
