/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DesignTag = {
  id: string;
  name: string;
};

/** @internal */
export const DesignTag$inboundSchema: z.ZodType<
  DesignTag,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
});

export function designTagFromJSON(
  jsonString: string,
): SafeParseResult<DesignTag, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DesignTag$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DesignTag' from JSON`,
  );
}
