/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DonateSupporter = {
  /**
   * The account id
   */
  accountId: number;
  /**
   * The avatar hash
   */
  avatar: string;
  /**
   * What this account donated this month, in cents
   */
  monthCents: number;
  /**
   * The account's display name
   */
  name: string;
  /**
   * The account's vanity, null if it has none
   */
  vanity: string | null;
};

/** @internal */
export const DonateSupporter$inboundSchema: z.ZodMiniType<
  DonateSupporter,
  unknown
> = z.object({
  accountId: z.int(),
  avatar: z.string(),
  monthCents: z.int(),
  name: z.string(),
  vanity: z.nullable(z.string()),
});

export function donateSupporterFromJSON(
  jsonString: string,
): SafeParseResult<DonateSupporter, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DonateSupporter$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DonateSupporter' from JSON`,
  );
}
