/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { ErrorDetail, ErrorDetail$inboundSchema } from "./errordetail.js";

export type ErrorModel = {
  /**
   * A URL to the JSON Schema for this object.
   */
  dollarSchema?: string | undefined;
  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail?: string | undefined;
  /**
   * Optional list of individual error details
   */
  errors?: Array<ErrorDetail> | null | undefined;
  /**
   * A URI reference that identifies the specific occurrence of the problem.
   */
  instance?: string | undefined;
  /**
   * HTTP status code
   */
  status?: number | undefined;
  /**
   * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
   */
  title?: string | undefined;
  /**
   * A URI reference to human-readable documentation for the error.
   */
  type: string;
};

/** @internal */
export const ErrorModel$inboundSchema: z.ZodMiniType<ErrorModel, unknown> = z
  .pipe(
    z.object({
      $schema: z.optional(z.string()),
      detail: z.optional(z.string()),
      errors: z.optional(z.nullable(z.array(ErrorDetail$inboundSchema))),
      instance: z.optional(z.string()),
      status: z.optional(z.int()),
      title: z.optional(z.string()),
      type: z._default(z.string(), "about:blank"),
    }),
    z.transform((v) => {
      return remap$(v, {
        "$schema": "dollarSchema",
      });
    }),
  );

export function errorModelFromJSON(
  jsonString: string,
): SafeParseResult<ErrorModel, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorModel$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorModel' from JSON`,
  );
}
