/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type EventMarketPriceTickData = {
  appId: number;
  averageListings: number;
  badgeType: string;
  buyOrderAveragePrice: number;
  cardAveragePrice: number;
  setBuyOrderPrice: number;
  setPrice: number;
  updatedAt: number;
};

/** @internal */
export const EventMarketPriceTickData$inboundSchema: z.ZodType<
  EventMarketPriceTickData,
  z.ZodTypeDef,
  unknown
> = z.object({
  appId: z.number().int(),
  averageListings: z.number().int(),
  badgeType: z.string(),
  buyOrderAveragePrice: z.number().int(),
  cardAveragePrice: z.number().int(),
  setBuyOrderPrice: z.number().int(),
  setPrice: z.number().int(),
  updatedAt: z.number().int(),
});

export function eventMarketPriceTickDataFromJSON(
  jsonString: string,
): SafeParseResult<EventMarketPriceTickData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EventMarketPriceTickData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EventMarketPriceTickData' from JSON`,
  );
}
