/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type IDSearch = {
  /**
   * Account ID to search for
   */
  accountId?: number | undefined;
  /**
   * SteamID64 to search for
   */
  steamId64?: string | undefined;
};

/** @internal */
export type IDSearch$Outbound = {
  accountId?: number | undefined;
  steamId64?: string | undefined;
};

/** @internal */
export const IDSearch$outboundSchema: z.ZodType<
  IDSearch$Outbound,
  z.ZodTypeDef,
  IDSearch
> = z.object({
  accountId: z.number().int().optional(),
  steamId64: z.string().optional(),
});

export function idSearchToJSON(idSearch: IDSearch): string {
  return JSON.stringify(IDSearch$outboundSchema.parse(idSearch));
}
