/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type KvListEntry = {
  key: string;
  namespace: string;
  updatedAt: Date;
  value: string;
};

/** @internal */
export const KvListEntry$inboundSchema: z.ZodType<
  KvListEntry,
  z.ZodTypeDef,
  unknown
> = z.object({
  key: z.string(),
  namespace: z.string(),
  updatedAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  value: z.string(),
});

export function kvListEntryFromJSON(
  jsonString: string,
): SafeParseResult<KvListEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KvListEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KvListEntry' from JSON`,
  );
}
