/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type LeaderboardState = {
  /**
   * The name of the state
   */
  name: string;
};

/** @internal */
export const LeaderboardState$inboundSchema: z.ZodType<
  LeaderboardState,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
});

export function leaderboardStateFromJSON(
  jsonString: string,
): SafeParseResult<LeaderboardState, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LeaderboardState$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LeaderboardState' from JSON`,
  );
}
