/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  LeaderboardCity,
  LeaderboardCity$inboundSchema,
} from "./leaderboardcity.js";
import {
  LeaderboardCountry,
  LeaderboardCountry$inboundSchema,
} from "./leaderboardcountry.js";
import {
  LeaderboardRegion,
  LeaderboardRegion$inboundSchema,
} from "./leaderboardregion.js";
import {
  LeaderboardState,
  LeaderboardState$inboundSchema,
} from "./leaderboardstate.js";
import { Role, Role$inboundSchema } from "./role.js";
import {
  SupporterStatus,
  SupporterStatus$inboundSchema,
} from "./supporterstatus.js";

/**
 * Donator name effect, none when unset or the account no longer holds an entitling role
 */
export const NameEffect = {
  None: "none",
  Rainbow: "rainbow",
  Glitch: "glitch",
  Shadow: "shadow",
  Neon: "neon",
  Retro: "retro",
  Stamped: "stamped",
  Shatter: "shatter",
  Typewriter: "typewriter",
  Vaporwave: "vaporwave",
  Sunken: "sunken",
} as const;
/**
 * Donator name effect, none when unset or the account no longer holds an entitling role
 */
export type NameEffect = OpenEnum<typeof NameEffect>;

/**
 * The privacy of the account
 */
export const Privacy = {
  Public: "public",
  Private: "private",
  FriendsOnly: "friends_only",
} as const;
/**
 * The privacy of the account
 */
export type Privacy = OpenEnum<typeof Privacy>;

export type LeaderboardAccount = {
  /**
   * The animated avatar of the account
   */
  animatedAvatar: string;
  /**
   * The number of apps the account has
   */
  apps: number;
  /**
   * The avatar hash of the account
   */
  avatar: string;
  /**
   * The avatar frame of the account
   */
  avatarFrame: string;
  /**
   * The number of awards the account has
   */
  awardsGiven: number;
  /**
   * The number of awards the account has
   */
  awardsReceived: number;
  /**
   * The background of the account
   */
  background: string;
  /**
   * The number of badges the account has
   */
  badges: number;
  /**
   * The number of bans
   */
  bans: number;
  city?: LeaderboardCity | null | undefined;
  country?: LeaderboardCountry | null | undefined;
  /**
   * The time the account was created
   */
  createdAt: Date;
  /**
   * The total of donations the account has
   */
  donated: number;
  /**
   * The economy ban of the account
   */
  economyBan: string;
  /**
   * The number of foil badges the account has
   */
  foilBadges: number;
  /**
   * The number of friends the account has
   */
  friends: number;
  /**
   * The number of game bans
   */
  gameBans: number;
  /**
   * The level of the account
   */
  level: number;
  /**
   * The mini background of the account
   */
  miniBackground: string;
  /**
   * The name of the account
   */
  name: string;
  /**
   * Donator name effect, none when unset or the account no longer holds an entitling role
   */
  nameEffect: NameEffect;
  /**
   * The number of normal badges the account has
   */
  normalBadges: number;
  /**
   * The playtime of the account
   */
  playtime: number;
  /**
   * The number of points the account has
   */
  pointsGiven: number;
  /**
   * The number of points the account has
   */
  pointsReceived: number;
  /**
   * The privacy of the account
   */
  privacy: Privacy;
  region?: LeaderboardRegion | null | undefined;
  /**
   * The roles of the account
   */
  roles: Array<Role> | null;
  state?: LeaderboardState | null | undefined;
  /**
   * The steam id
   */
  steamId: string;
  /**
   * The steam sets score
   */
  steamSetsScore: number;
  /**
   * The vanity of the account
   */
  steamSetsVanity: string;
  /**
   * The vanity of the account
   */
  steamVanity: string;
  supporter?: SupporterStatus | undefined;
  /**
   * Donator profile theme color as #RRGGBB (no alpha), null when unset or the account no longer holds an entitling role
   */
  themeColor: string | null;
  /**
   * The number of vac bans
   */
  vacBans: number;
  /**
   * The number of xp the account has
   */
  xp: number;
};

/** @internal */
export const NameEffect$inboundSchema: z.ZodMiniType<NameEffect, unknown> =
  openEnums.inboundSchema(NameEffect);

/** @internal */
export const Privacy$inboundSchema: z.ZodMiniType<Privacy, unknown> = openEnums
  .inboundSchema(Privacy);

/** @internal */
export const LeaderboardAccount$inboundSchema: z.ZodMiniType<
  LeaderboardAccount,
  unknown
> = z.object({
  animatedAvatar: z.string(),
  apps: z.int(),
  avatar: z.string(),
  avatarFrame: z.string(),
  awardsGiven: z.int(),
  awardsReceived: z.int(),
  background: z.string(),
  badges: z.int(),
  bans: z.int(),
  city: z.optional(z.nullable(LeaderboardCity$inboundSchema)),
  country: z.optional(z.nullable(LeaderboardCountry$inboundSchema)),
  createdAt: z.pipe(
    z.iso.datetime({ offset: true }),
    z.transform(v => new Date(v)),
  ),
  donated: z.int(),
  economyBan: z.string(),
  foilBadges: z.int(),
  friends: z.int(),
  gameBans: z.int(),
  level: z.int(),
  miniBackground: z.string(),
  name: z.string(),
  nameEffect: NameEffect$inboundSchema,
  normalBadges: z.int(),
  playtime: z.int(),
  pointsGiven: z.int(),
  pointsReceived: z.int(),
  privacy: Privacy$inboundSchema,
  region: z.optional(z.nullable(LeaderboardRegion$inboundSchema)),
  roles: z.nullable(z.array(Role$inboundSchema)),
  state: z.optional(z.nullable(LeaderboardState$inboundSchema)),
  steamId: z.string(),
  steamSetsScore: z.int(),
  steamSetsVanity: z.string(),
  steamVanity: z.string(),
  supporter: z.optional(SupporterStatus$inboundSchema),
  themeColor: z.nullable(z.string()),
  vacBans: z.int(),
  xp: z.int(),
});

export function leaderboardAccountFromJSON(
  jsonString: string,
): SafeParseResult<LeaderboardAccount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LeaderboardAccount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LeaderboardAccount' from JSON`,
  );
}
