/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Country, Country$inboundSchema } from "./country.js";

export type Region = {
  /**
   * The countries of the region
   */
  countries: Array<Country> | null;
  /**
   * The name of the region
   */
  name: string;
};

/** @internal */
export const Region$inboundSchema: z.ZodType<Region, z.ZodTypeDef, unknown> = z
  .object({
    countries: z.nullable(z.array(Country$inboundSchema)),
    name: z.string(),
  });

export function regionFromJSON(
  jsonString: string,
): SafeParseResult<Region, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Region$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Region' from JSON`,
  );
}
