/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * Which search surface to query.
 */
export const SearchGetTrendingRequestBodySource = {
  Badge: "badge",
  App: "app",
  Account: "account",
} as const;
/**
 * Which search surface to query.
 */
export type SearchGetTrendingRequestBodySource = OpenEnum<
  typeof SearchGetTrendingRequestBodySource
>;

/**
 * Lookback window for trending compute.
 */
export const SearchGetTrendingRequestBodyWindow = {
  TwentyFourh: "24h",
  Sevend: "7d",
  Thirtyd: "30d",
} as const;
/**
 * Lookback window for trending compute.
 */
export type SearchGetTrendingRequestBodyWindow = OpenEnum<
  typeof SearchGetTrendingRequestBodyWindow
>;

export type SearchGetTrendingRequestBody = {
  /**
   * Max queries returned. Default 100.
   */
  limit?: number | undefined;
  /**
   * Which search surface to query.
   */
  source: SearchGetTrendingRequestBodySource;
  /**
   * Lookback window for trending compute.
   */
  window: SearchGetTrendingRequestBodyWindow;
};

/** @internal */
export const SearchGetTrendingRequestBodySource$outboundSchema: z.ZodMiniType<
  string,
  SearchGetTrendingRequestBodySource
> = openEnums.outboundSchema(SearchGetTrendingRequestBodySource);

/** @internal */
export const SearchGetTrendingRequestBodyWindow$outboundSchema: z.ZodMiniType<
  string,
  SearchGetTrendingRequestBodyWindow
> = openEnums.outboundSchema(SearchGetTrendingRequestBodyWindow);

/** @internal */
export type SearchGetTrendingRequestBody$Outbound = {
  limit?: number | undefined;
  source: string;
  window: string;
};

/** @internal */
export const SearchGetTrendingRequestBody$outboundSchema: z.ZodMiniType<
  SearchGetTrendingRequestBody$Outbound,
  SearchGetTrendingRequestBody
> = z.object({
  limit: z.optional(z.int()),
  source: SearchGetTrendingRequestBodySource$outboundSchema,
  window: SearchGetTrendingRequestBodyWindow$outboundSchema,
});

export function searchGetTrendingRequestBodyToJSON(
  searchGetTrendingRequestBody: SearchGetTrendingRequestBody,
): string {
  return JSON.stringify(
    SearchGetTrendingRequestBody$outboundSchema.parse(
      searchGetTrendingRequestBody,
    ),
  );
}
