/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SiteSubscribeHeartbeat = {
  heartbeat: number;
};

/** @internal */
export const SiteSubscribeHeartbeat$inboundSchema: z.ZodType<
  SiteSubscribeHeartbeat,
  z.ZodTypeDef,
  unknown
> = z.object({
  heartbeat: z.number().int(),
});

export function siteSubscribeHeartbeatFromJSON(
  jsonString: string,
): SafeParseResult<SiteSubscribeHeartbeat, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SiteSubscribeHeartbeat$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SiteSubscribeHeartbeat' from JSON`,
  );
}
