/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { UpdateError, UpdateError$inboundSchema } from "./updateerror.js";
import { UpdateStep, UpdateStep$inboundSchema } from "./updatestep.js";

export type UpdateProgress = {
  /**
   * The account this progress snapshot belongs to.
   */
  accountId: number;
  /**
   * The step the update is on now.
   */
  currentStep: string;
  error?: UpdateError | undefined;
  /**
   * The time the update finished, in UTC. Set on success or failure.
   */
  finishedAt?: Date | undefined;
  /**
   * How far the update has progressed, from 0 to 100.
   */
  percent: number;
  /**
   * Reserved for a future queue that can report a position. Always absent today.
   */
  queuePosition?: number | undefined;
  /**
   * The time the update was queued, in UTC.
   */
  queuedAt?: Date | undefined;
  /**
   * An ID for the update run. Compare it to tell a new run from a later event of the same run.
   */
  runId: string;
  /**
   * The time the update started running, in UTC.
   */
  startedAt?: Date | undefined;
  /**
   * The overall status: undefined, pending, in_progress, completed, or failed.
   */
  status: string;
  /**
   * Every step in the pipeline, in run order, with its own status.
   */
  steps: Array<UpdateStep> | null;
  /**
   * The time this snapshot was last written, in UTC.
   */
  updatedAt: Date;
};

/** @internal */
export const UpdateProgress$inboundSchema: z.ZodMiniType<
  UpdateProgress,
  unknown
> = z.object({
  accountId: z.int(),
  currentStep: z.string(),
  error: z.optional(UpdateError$inboundSchema),
  finishedAt: z.optional(
    z.pipe(z.iso.datetime({ offset: true }), z.transform(v => new Date(v))),
  ),
  percent: z.int(),
  queuePosition: z.optional(z.int()),
  queuedAt: z.optional(
    z.pipe(z.iso.datetime({ offset: true }), z.transform(v => new Date(v))),
  ),
  runId: z.string(),
  startedAt: z.optional(
    z.pipe(z.iso.datetime({ offset: true }), z.transform(v => new Date(v))),
  ),
  status: z.string(),
  steps: z.nullable(z.array(UpdateStep$inboundSchema)),
  updatedAt: z.pipe(
    z.iso.datetime({ offset: true }),
    z.transform(v => new Date(v)),
  ),
});

export function updateProgressFromJSON(
  jsonString: string,
): SafeParseResult<UpdateProgress, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateProgress$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateProgress' from JSON`,
  );
}
