/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { HistoryValue, HistoryValue$inboundSchema } from "./historyvalue.js";

export type V1AccountVanityUpdate = {
  /**
   * The time the vanity was updated
   */
  updatedAt: Date;
  vanity: HistoryValue;
};

/** @internal */
export const V1AccountVanityUpdate$inboundSchema: z.ZodMiniType<
  V1AccountVanityUpdate,
  unknown
> = z.object({
  updatedAt: z.pipe(
    z.iso.datetime({ offset: true }),
    z.transform(v => new Date(v)),
  ),
  vanity: HistoryValue$inboundSchema,
});

export function v1AccountVanityUpdateFromJSON(
  jsonString: string,
): SafeParseResult<V1AccountVanityUpdate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1AccountVanityUpdate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1AccountVanityUpdate' from JSON`,
  );
}
