/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { ComparedTuple, ComparedTuple$inboundSchema } from "./comparedtuple.js";
import {
  ResolvedAccount,
  ResolvedAccount$inboundSchema,
} from "./resolvedaccount.js";

export type V1AccountCompareBadgesResponseBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  dollarSchema?: string | undefined;
  accounts: Array<ResolvedAccount> | null;
  /**
   * The number of pages
   */
  pages: number;
  /**
   * The total number of hits for all pages
   */
  totalHits: number;
  tuples: Array<ComparedTuple> | null;
};

/** @internal */
export const V1AccountCompareBadgesResponseBody$inboundSchema: z.ZodType<
  V1AccountCompareBadgesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  $schema: z.string().optional(),
  accounts: z.nullable(z.array(ResolvedAccount$inboundSchema)),
  pages: z.number().int(),
  totalHits: z.number().int(),
  tuples: z.nullable(z.array(ComparedTuple$inboundSchema)),
}).transform((v) => {
  return remap$(v, {
    "$schema": "dollarSchema",
  });
});

export function v1AccountCompareBadgesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<V1AccountCompareBadgesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V1AccountCompareBadgesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1AccountCompareBadgesResponseBody' from JSON`,
  );
}
