/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1AccountListFriendsStats = {
  /**
   * Average badge count of all friends, rounded
   */
  averageBadges: number;
  /**
   * Average Steam level of all friends, rounded
   */
  averageLevel: number;
};

/** @internal */
export const V1AccountListFriendsStats$inboundSchema: z.ZodMiniType<
  V1AccountListFriendsStats,
  unknown
> = z.object({
  averageBadges: z.int(),
  averageLevel: z.int(),
});

export function v1AccountListFriendsStatsFromJSON(
  jsonString: string,
): SafeParseResult<V1AccountListFriendsStats, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1AccountListFriendsStats$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1AccountListFriendsStats' from JSON`,
  );
}
