/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  BestLeaderboardRank,
  BestLeaderboardRank$inboundSchema,
} from "./bestleaderboardrank.js";
import { Connection, Connection$inboundSchema } from "./connection.js";
import {
  CurrentLeaderboardRank,
  CurrentLeaderboardRank$inboundSchema,
} from "./currentleaderboardrank.js";
import {
  LeaderboardCity,
  LeaderboardCity$inboundSchema,
} from "./leaderboardcity.js";
import {
  LeaderboardCountry,
  LeaderboardCountry$inboundSchema,
} from "./leaderboardcountry.js";
import {
  LeaderboardRegion,
  LeaderboardRegion$inboundSchema,
} from "./leaderboardregion.js";
import {
  LeaderboardState,
  LeaderboardState$inboundSchema,
} from "./leaderboardstate.js";
import { Role, Role$inboundSchema } from "./role.js";
import {
  SupporterStatus,
  SupporterStatus$inboundSchema,
} from "./supporterstatus.js";

/**
 * The privacy of the account
 */
export const AppPrivacy = {
  Private: "private",
  Public: "public",
  FriendsOnly: "friends_only",
} as const;
/**
 * The privacy of the account
 */
export type AppPrivacy = OpenEnum<typeof AppPrivacy>;

/**
 * The privacy of the account
 */
export const FriendPrivacy = {
  Private: "private",
  Public: "public",
  FriendsOnly: "friends_only",
} as const;
/**
 * The privacy of the account
 */
export type FriendPrivacy = OpenEnum<typeof FriendPrivacy>;

export const LastQueueStatus = {
  Undefined: "undefined",
  Pending: "pending",
  InProgress: "in_progress",
  Completed: "completed",
} as const;
export type LastQueueStatus = OpenEnum<typeof LastQueueStatus>;

/**
 * Donator name effect, none when unset or the account no longer holds an entitling role
 */
export const V1AccountGetInfoResponseBodyNameEffect = {
  None: "none",
  Rainbow: "rainbow",
  Glitch: "glitch",
  Shadow: "shadow",
  Neon: "neon",
  Retro: "retro",
  Stamped: "stamped",
  Shatter: "shatter",
  Typewriter: "typewriter",
  Vaporwave: "vaporwave",
  Sunken: "sunken",
} as const;
/**
 * Donator name effect, none when unset or the account no longer holds an entitling role
 */
export type V1AccountGetInfoResponseBodyNameEffect = OpenEnum<
  typeof V1AccountGetInfoResponseBodyNameEffect
>;

/**
 * The privacy of the account
 */
export const V1AccountGetInfoResponseBodyPrivacy = {
  Private: "private",
  Public: "public",
  FriendsOnly: "friends_only",
} as const;
/**
 * The privacy of the account
 */
export type V1AccountGetInfoResponseBodyPrivacy = OpenEnum<
  typeof V1AccountGetInfoResponseBodyPrivacy
>;

export type V1AccountGetInfoResponseBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  dollarSchema?: string | undefined;
  /**
   * The account id
   */
  accountId: number;
  /**
   * The animated avatar of the account
   */
  animatedAvatar: string;
  /**
   * The privacy of the account
   */
  appPrivacy: AppPrivacy;
  /**
   * The number of apps the account has
   */
  apps: number;
  /**
   * The avatar hash of the account
   */
  avatar: string;
  /**
   * The avatar frame of the account
   */
  avatarFrame: string;
  /**
   * The number of awards the account has
   */
  awardsGiven: number;
  /**
   * The number of awards the account has
   */
  awardsReceived: number;
  /**
   * The background of the account
   */
  background: string;
  /**
   * The number of badges the account has
   */
  badges: number;
  /**
   * The number of bans
   */
  bans: number;
  city?: LeaderboardCity | null | undefined;
  /**
   * If the account is community banned or not
   */
  communityBan: boolean;
  /**
   * The connections of the account
   */
  connections: Array<Connection> | null;
  country?: LeaderboardCountry | null | undefined;
  /**
   * The time the account was created
   */
  createdAt: Date | null;
  /**
   * The current best ranks
   */
  currentBestRanks: Array<BestLeaderboardRank> | null;
  /**
   * The current ranks
   */
  currentRanks: Array<CurrentLeaderboardRank> | null;
  /**
   * The total of donations the account has
   */
  donated: number;
  /**
   * The economy ban of the account
   */
  economyBan: string;
  /**
   * The number of foil badges the account has
   */
  foilBadges: number;
  /**
   * The privacy of the account
   */
  friendPrivacy: FriendPrivacy;
  /**
   * The number of friends the account has
   */
  friends: number;
  /**
   * The number of game bans
   */
  gameBans: number;
  /**
   * The Last date the account got a ban on
   */
  lastBanDate: Date | null;
  lastQueueStatus: LastQueueStatus;
  /**
   * The level of the account
   */
  level: number;
  /**
   * The mini background of the account
   */
  miniBackground: string;
  /**
   * The name of the account
   */
  name: string;
  /**
   * Donator name effect, none when unset or the account no longer holds an entitling role
   */
  nameEffect: V1AccountGetInfoResponseBodyNameEffect;
  /**
   * The time the account is allowed to be refreshed
   */
  nextAllowedTime: Date;
  /**
   * The number of normal badges the account has
   */
  normalBadges: number;
  /**
   * The playtime of the account
   */
  playtime: number;
  /**
   * The number of points the account has
   */
  pointsGiven: number;
  /**
   * The number of points the account has
   */
  pointsReceived: number;
  /**
   * The privacy of the account
   */
  privacy: V1AccountGetInfoResponseBodyPrivacy;
  region?: LeaderboardRegion | null | undefined;
  /**
   * The roles of the account
   */
  roles: Array<Role> | null;
  /**
   * The shortlink domain of the account, is to be used with their steamsets vanity
   */
  shortlinkDomain: string | null;
  state?: LeaderboardState | null | undefined;
  /**
   * The steam id
   */
  steamId: string;
  /**
   * The steam sets score
   */
  steamSetsScore: number;
  /**
   * The vanity of the account
   */
  steamSetsVanity: string;
  /**
   * The vanity of the account
   */
  steamVanity: string;
  supporter: SupporterStatus;
  /**
   * The theme of the account
   */
  theme: string;
  /**
   * Donator profile theme color as #RRGGBB (no alpha), null when unset or the account no longer holds an entitling role
   */
  themeColor: string | null;
  /**
   * The time the account was updated
   */
  updatedAt: Date | null;
  /**
   * The number of vac bans
   */
  vacBans: number;
  /**
   * The number of xp the account has
   */
  xp: number;
};

/** @internal */
export const AppPrivacy$inboundSchema: z.ZodMiniType<AppPrivacy, unknown> =
  openEnums.inboundSchema(AppPrivacy);

/** @internal */
export const FriendPrivacy$inboundSchema: z.ZodMiniType<
  FriendPrivacy,
  unknown
> = openEnums.inboundSchema(FriendPrivacy);

/** @internal */
export const LastQueueStatus$inboundSchema: z.ZodMiniType<
  LastQueueStatus,
  unknown
> = openEnums.inboundSchema(LastQueueStatus);

/** @internal */
export const V1AccountGetInfoResponseBodyNameEffect$inboundSchema:
  z.ZodMiniType<V1AccountGetInfoResponseBodyNameEffect, unknown> = openEnums
    .inboundSchema(V1AccountGetInfoResponseBodyNameEffect);

/** @internal */
export const V1AccountGetInfoResponseBodyPrivacy$inboundSchema: z.ZodMiniType<
  V1AccountGetInfoResponseBodyPrivacy,
  unknown
> = openEnums.inboundSchema(V1AccountGetInfoResponseBodyPrivacy);

/** @internal */
export const V1AccountGetInfoResponseBody$inboundSchema: z.ZodMiniType<
  V1AccountGetInfoResponseBody,
  unknown
> = z.pipe(
  z.object({
    $schema: z.optional(z.string()),
    accountId: z.int(),
    animatedAvatar: z.string(),
    appPrivacy: AppPrivacy$inboundSchema,
    apps: z.int(),
    avatar: z.string(),
    avatarFrame: z.string(),
    awardsGiven: z.int(),
    awardsReceived: z.int(),
    background: z.string(),
    badges: z.int(),
    bans: z.int(),
    city: z.optional(z.nullable(LeaderboardCity$inboundSchema)),
    communityBan: z.boolean(),
    connections: z.nullable(z.array(Connection$inboundSchema)),
    country: z.optional(z.nullable(LeaderboardCountry$inboundSchema)),
    createdAt: z.nullable(
      z.pipe(z.iso.datetime({ offset: true }), z.transform(v => new Date(v))),
    ),
    currentBestRanks: z.nullable(z.array(BestLeaderboardRank$inboundSchema)),
    currentRanks: z.nullable(z.array(CurrentLeaderboardRank$inboundSchema)),
    donated: z.int(),
    economyBan: z.string(),
    foilBadges: z.int(),
    friendPrivacy: FriendPrivacy$inboundSchema,
    friends: z.int(),
    gameBans: z.int(),
    lastBanDate: z.nullable(
      z.pipe(z.iso.datetime({ offset: true }), z.transform(v => new Date(v))),
    ),
    lastQueueStatus: LastQueueStatus$inboundSchema,
    level: z.int(),
    miniBackground: z.string(),
    name: z.string(),
    nameEffect: V1AccountGetInfoResponseBodyNameEffect$inboundSchema,
    nextAllowedTime: z.pipe(
      z.iso.datetime({ offset: true }),
      z.transform(v => new Date(v)),
    ),
    normalBadges: z.int(),
    playtime: z.int(),
    pointsGiven: z.int(),
    pointsReceived: z.int(),
    privacy: V1AccountGetInfoResponseBodyPrivacy$inboundSchema,
    region: z.optional(z.nullable(LeaderboardRegion$inboundSchema)),
    roles: z.nullable(z.array(Role$inboundSchema)),
    shortlinkDomain: z.nullable(z.string()),
    state: z.optional(z.nullable(LeaderboardState$inboundSchema)),
    steamId: z.string(),
    steamSetsScore: z.int(),
    steamSetsVanity: z.string(),
    steamVanity: z.string(),
    supporter: SupporterStatus$inboundSchema,
    theme: z.string(),
    themeColor: z.nullable(z.string()),
    updatedAt: z.nullable(
      z.pipe(z.iso.datetime({ offset: true }), z.transform(v => new Date(v))),
    ),
    vacBans: z.int(),
    xp: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "$schema": "dollarSchema",
    });
  }),
);

export function v1AccountGetInfoResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<V1AccountGetInfoResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1AccountGetInfoResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1AccountGetInfoResponseBody' from JSON`,
  );
}
