/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1AccountCreateConnectionResponseBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  dollarSchema?: string | undefined;
  /**
   * Code that has to be used to verify domain connections
   */
  code: string;
  /**
   * Public ID of the connection only for domain connections
   */
  connectionId?: string | null | undefined;
};

/** @internal */
export const V1AccountCreateConnectionResponseBody$inboundSchema: z.ZodType<
  V1AccountCreateConnectionResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  $schema: z.string().optional(),
  code: z.string(),
  connectionId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "$schema": "dollarSchema",
  });
});

/** @internal */
export type V1AccountCreateConnectionResponseBody$Outbound = {
  $schema?: string | undefined;
  code: string;
  connectionId?: string | null | undefined;
};

/** @internal */
export const V1AccountCreateConnectionResponseBody$outboundSchema: z.ZodType<
  V1AccountCreateConnectionResponseBody$Outbound,
  z.ZodTypeDef,
  V1AccountCreateConnectionResponseBody
> = z.object({
  dollarSchema: z.string().optional(),
  code: z.string(),
  connectionId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    dollarSchema: "$schema",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1AccountCreateConnectionResponseBody$ {
  /** @deprecated use `V1AccountCreateConnectionResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    V1AccountCreateConnectionResponseBody$inboundSchema;
  /** @deprecated use `V1AccountCreateConnectionResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    V1AccountCreateConnectionResponseBody$outboundSchema;
  /** @deprecated use `V1AccountCreateConnectionResponseBody$Outbound` instead. */
  export type Outbound = V1AccountCreateConnectionResponseBody$Outbound;
}

export function v1AccountCreateConnectionResponseBodyToJSON(
  v1AccountCreateConnectionResponseBody: V1AccountCreateConnectionResponseBody,
): string {
  return JSON.stringify(
    V1AccountCreateConnectionResponseBody$outboundSchema.parse(
      v1AccountCreateConnectionResponseBody,
    ),
  );
}

export function v1AccountCreateConnectionResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<V1AccountCreateConnectionResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V1AccountCreateConnectionResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1AccountCreateConnectionResponseBody' from JSON`,
  );
}
