/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { HistoryValue, HistoryValue$inboundSchema } from "./historyvalue.js";

export type V1AccountLocationUpdate = {
  city: HistoryValue;
  countryCode: HistoryValue;
  countryName: HistoryValue;
  region: HistoryValue;
  state: HistoryValue;
  /**
   * The time the location was updated
   */
  updatedAt: Date;
};

/** @internal */
export const V1AccountLocationUpdate$inboundSchema: z.ZodType<
  V1AccountLocationUpdate,
  z.ZodTypeDef,
  unknown
> = z.object({
  city: HistoryValue$inboundSchema,
  countryCode: HistoryValue$inboundSchema,
  countryName: HistoryValue$inboundSchema,
  region: HistoryValue$inboundSchema,
  state: HistoryValue$inboundSchema,
  updatedAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
});

export function v1AccountLocationUpdateFromJSON(
  jsonString: string,
): SafeParseResult<V1AccountLocationUpdate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1AccountLocationUpdate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1AccountLocationUpdate' from JSON`,
  );
}
