/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1AccountDeveloperAppUpdateResponseBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  dollarSchema?: string | undefined;
  /**
   * The generated API Key
   */
  apiKey: string | null;
};

/** @internal */
export const V1AccountDeveloperAppUpdateResponseBody$inboundSchema: z.ZodType<
  V1AccountDeveloperAppUpdateResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  $schema: z.string().optional(),
  apiKey: z.nullable(z.string()),
}).transform((v) => {
  return remap$(v, {
    "$schema": "dollarSchema",
  });
});

export function v1AccountDeveloperAppUpdateResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  V1AccountDeveloperAppUpdateResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V1AccountDeveloperAppUpdateResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V1AccountDeveloperAppUpdateResponseBody' from JSON`,
  );
}
