/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  AccountSearch,
  AccountSearch$Outbound,
  AccountSearch$outboundSchema,
} from "./accountsearch.js";

export type V1AccountFindFriendPathRequestBody = {
  /**
   * Accounts to exclude from all paths. From/To are never excluded even if listed.
   */
  exclude?: Array<AccountSearch> | null | undefined;
  from: AccountSearch;
  /**
   * Max number of paths to return (default 10, capped at 50). A direct friendship always returns a single path regardless of this value.
   */
  maxPaths?: number | undefined;
  to: AccountSearch;
};

/** @internal */
export type V1AccountFindFriendPathRequestBody$Outbound = {
  exclude?: Array<AccountSearch$Outbound> | null | undefined;
  from: AccountSearch$Outbound;
  maxPaths?: number | undefined;
  to: AccountSearch$Outbound;
};

/** @internal */
export const V1AccountFindFriendPathRequestBody$outboundSchema: z.ZodMiniType<
  V1AccountFindFriendPathRequestBody$Outbound,
  V1AccountFindFriendPathRequestBody
> = z.object({
  exclude: z.optional(z.nullable(z.array(AccountSearch$outboundSchema))),
  from: AccountSearch$outboundSchema,
  maxPaths: z.optional(z.int()),
  to: AccountSearch$outboundSchema,
});

export function v1AccountFindFriendPathRequestBodyToJSON(
  v1AccountFindFriendPathRequestBody: V1AccountFindFriendPathRequestBody,
): string {
  return JSON.stringify(
    V1AccountFindFriendPathRequestBody$outboundSchema.parse(
      v1AccountFindFriendPathRequestBody,
    ),
  );
}
