/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1AccountBadgeCountStats = {
  foil: number;
  normal: number;
  special: number;
};

/** @internal */
export const V1AccountBadgeCountStats$inboundSchema: z.ZodType<
  V1AccountBadgeCountStats,
  z.ZodTypeDef,
  unknown
> = z.object({
  foil: z.number().int(),
  normal: z.number().int(),
  special: z.number().int(),
});

export function v1AccountBadgeCountStatsFromJSON(
  jsonString: string,
): SafeParseResult<V1AccountBadgeCountStats, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1AccountBadgeCountStats$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1AccountBadgeCountStats' from JSON`,
  );
}
