/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1ActivityStreamHeartbeat = {
  heartbeat: number;
};

/** @internal */
export const V1ActivityStreamHeartbeat$inboundSchema: z.ZodMiniType<
  V1ActivityStreamHeartbeat,
  unknown
> = z.object({
  heartbeat: z.int(),
});

export function v1ActivityStreamHeartbeatFromJSON(
  jsonString: string,
): SafeParseResult<V1ActivityStreamHeartbeat, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1ActivityStreamHeartbeat$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1ActivityStreamHeartbeat' from JSON`,
  );
}
