/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type V1AccountUpdateConnectionRequestBody = {
  /**
   * The connection id to update
   */
  connectionId: string;
  /**
   * Whether the connection should be hidden or not
   */
  hidden: boolean;
};

/** @internal */
export type V1AccountUpdateConnectionRequestBody$Outbound = {
  connectionId: string;
  hidden: boolean;
};

/** @internal */
export const V1AccountUpdateConnectionRequestBody$outboundSchema: z.ZodType<
  V1AccountUpdateConnectionRequestBody$Outbound,
  z.ZodTypeDef,
  V1AccountUpdateConnectionRequestBody
> = z.object({
  connectionId: z.string(),
  hidden: z.boolean(),
});

export function v1AccountUpdateConnectionRequestBodyToJSON(
  v1AccountUpdateConnectionRequestBody: V1AccountUpdateConnectionRequestBody,
): string {
  return JSON.stringify(
    V1AccountUpdateConnectionRequestBody$outboundSchema.parse(
      v1AccountUpdateConnectionRequestBody,
    ),
  );
}
