/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1AccountDeveloperAppDeleteResponseBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  dollarSchema?: string | undefined;
};

/** @internal */
export const V1AccountDeveloperAppDeleteResponseBody$inboundSchema: z.ZodType<
  V1AccountDeveloperAppDeleteResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  $schema: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "$schema": "dollarSchema",
  });
});

/** @internal */
export type V1AccountDeveloperAppDeleteResponseBody$Outbound = {
  $schema?: string | undefined;
};

/** @internal */
export const V1AccountDeveloperAppDeleteResponseBody$outboundSchema: z.ZodType<
  V1AccountDeveloperAppDeleteResponseBody$Outbound,
  z.ZodTypeDef,
  V1AccountDeveloperAppDeleteResponseBody
> = z.object({
  dollarSchema: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    dollarSchema: "$schema",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1AccountDeveloperAppDeleteResponseBody$ {
  /** @deprecated use `V1AccountDeveloperAppDeleteResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    V1AccountDeveloperAppDeleteResponseBody$inboundSchema;
  /** @deprecated use `V1AccountDeveloperAppDeleteResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    V1AccountDeveloperAppDeleteResponseBody$outboundSchema;
  /** @deprecated use `V1AccountDeveloperAppDeleteResponseBody$Outbound` instead. */
  export type Outbound = V1AccountDeveloperAppDeleteResponseBody$Outbound;
}

export function v1AccountDeveloperAppDeleteResponseBodyToJSON(
  v1AccountDeveloperAppDeleteResponseBody:
    V1AccountDeveloperAppDeleteResponseBody,
): string {
  return JSON.stringify(
    V1AccountDeveloperAppDeleteResponseBody$outboundSchema.parse(
      v1AccountDeveloperAppDeleteResponseBody,
    ),
  );
}

export function v1AccountDeveloperAppDeleteResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  V1AccountDeveloperAppDeleteResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V1AccountDeveloperAppDeleteResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V1AccountDeveloperAppDeleteResponseBody' from JSON`,
  );
}
