/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  V1AccountFriend,
  V1AccountFriend$inboundSchema,
} from "./v1accountfriend.js";

export type V1AccountListFriendsResponseBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  dollarSchema?: string | undefined;
  friends: Array<V1AccountFriend | null> | null;
  /**
   * Cursor for the next page, null when this is the last page
   */
  nextCursor: string | null;
  /**
   * Total number of friends across all pages
   */
  total: number;
};

/** @internal */
export const V1AccountListFriendsResponseBody$inboundSchema: z.ZodType<
  V1AccountListFriendsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  $schema: z.string().optional(),
  friends: z.nullable(z.array(z.nullable(V1AccountFriend$inboundSchema))),
  nextCursor: z.nullable(z.string()),
  total: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "$schema": "dollarSchema",
  });
});

export function v1AccountListFriendsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<V1AccountListFriendsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1AccountListFriendsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1AccountListFriendsResponseBody' from JSON`,
  );
}
