/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type V1AccountReconnectRequestBody = {
  /**
   * The code from the oauth2 provider to re-verify
   */
  code: string;
  /**
   * The connection id to reconnect
   */
  connectionId: string;
};

/** @internal */
export type V1AccountReconnectRequestBody$Outbound = {
  code: string;
  connectionId: string;
};

/** @internal */
export const V1AccountReconnectRequestBody$outboundSchema: z.ZodType<
  V1AccountReconnectRequestBody$Outbound,
  z.ZodTypeDef,
  V1AccountReconnectRequestBody
> = z.object({
  code: z.string(),
  connectionId: z.string(),
});

export function v1AccountReconnectRequestBodyToJSON(
  v1AccountReconnectRequestBody: V1AccountReconnectRequestBody,
): string {
  return JSON.stringify(
    V1AccountReconnectRequestBody$outboundSchema.parse(
      v1AccountReconnectRequestBody,
    ),
  );
}
