/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1AccountGetMetaResponseBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  dollarSchema?: string | undefined;
  steamAvatarHashOfTheAccount: string;
  description: string;
  /**
   * Use this + cdn.steamsets.com/og/account/steamId.png as url
   */
  steamId: string;
  title: string;
};

/** @internal */
export const V1AccountGetMetaResponseBody$inboundSchema: z.ZodType<
  V1AccountGetMetaResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  $schema: z.string().optional(),
  "Steam Avatar hash of the account": z.string(),
  description: z.string(),
  steamId: z.string(),
  title: z.string(),
}).transform((v) => {
  return remap$(v, {
    "$schema": "dollarSchema",
    "Steam Avatar hash of the account": "steamAvatarHashOfTheAccount",
  });
});

export function v1AccountGetMetaResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<V1AccountGetMetaResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1AccountGetMetaResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1AccountGetMetaResponseBody' from JSON`,
  );
}
