/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1AccountBadgeOwnedBadge = {
  /**
   * The app id
   */
  appId: number;
  /**
   * The badge id
   */
  badgeId: string;
  /**
   * Whether the badge is foil or not
   */
  isFoil: boolean;
  /**
   * The level of the badge
   */
  level: number;
  /**
   * The internal steam id badge id
   */
  steamId: number;
};

/** @internal */
export const V1AccountBadgeOwnedBadge$inboundSchema: z.ZodMiniType<
  V1AccountBadgeOwnedBadge,
  unknown
> = z.object({
  appId: z.int(),
  badgeId: z.string(),
  isFoil: z.boolean(),
  level: z.int(),
  steamId: z.int(),
});

export function v1AccountBadgeOwnedBadgeFromJSON(
  jsonString: string,
): SafeParseResult<V1AccountBadgeOwnedBadge, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1AccountBadgeOwnedBadge$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1AccountBadgeOwnedBadge' from JSON`,
  );
}
