/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  V1ActivityEvent,
  V1ActivityEvent$inboundSchema,
} from "./v1activityevent.js";

export type V1ActivityListAccountFeedResponseBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  dollarSchema?: string | undefined;
  events: Array<V1ActivityEvent> | null;
  /**
   * Pass as cursor to fetch the next page. Absent when there are no more events.
   */
  nextCursor?: string | undefined;
};

/** @internal */
export const V1ActivityListAccountFeedResponseBody$inboundSchema: z.ZodMiniType<
  V1ActivityListAccountFeedResponseBody,
  unknown
> = z.pipe(
  z.object({
    $schema: z.optional(z.string()),
    events: z.nullable(z.array(V1ActivityEvent$inboundSchema)),
    nextCursor: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "$schema": "dollarSchema",
    });
  }),
);

export function v1ActivityListAccountFeedResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<V1ActivityListAccountFeedResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V1ActivityListAccountFeedResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1ActivityListAccountFeedResponseBody' from JSON`,
  );
}
