/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1ActivityStreamFeedEvent = {
  accountId: number;
  badgeId?: string | undefined;
  badgeLevel?: number | undefined;
  countryId?: number | undefined;
  eventType: string;
  globalCraftOrder?: number | undefined;
  isFoil?: boolean | undefined;
  leaderboard?: string | undefined;
  level?: number | undefined;
  locationType?: string | undefined;
  newRank?: number | undefined;
  occurredAt: Date;
  previousLevel?: number | undefined;
  previousRank?: number | undefined;
  rankBucket?: string | undefined;
  regionId?: number | undefined;
};

/** @internal */
export const V1ActivityStreamFeedEvent$inboundSchema: z.ZodType<
  V1ActivityStreamFeedEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  accountId: z.number().int(),
  badgeId: z.string().optional(),
  badgeLevel: z.number().int().optional(),
  countryId: z.number().int().optional(),
  eventType: z.string(),
  globalCraftOrder: z.number().int().optional(),
  isFoil: z.boolean().optional(),
  leaderboard: z.string().optional(),
  level: z.number().int().optional(),
  locationType: z.string().optional(),
  newRank: z.number().int().optional(),
  occurredAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  previousLevel: z.number().int().optional(),
  previousRank: z.number().int().optional(),
  rankBucket: z.string().optional(),
  regionId: z.number().int().optional(),
});

export function v1ActivityStreamFeedEventFromJSON(
  jsonString: string,
): SafeParseResult<V1ActivityStreamFeedEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1ActivityStreamFeedEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1ActivityStreamFeedEvent' from JSON`,
  );
}
