/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The stored name effect after the update
 */
export const V1AccountUpdateCosmeticsBodyNameEffect = {
  None: "none",
  Rainbow: "rainbow",
  Glitch: "glitch",
  Shadow: "shadow",
  Neon: "neon",
  Retro: "retro",
  Stamped: "stamped",
  Shatter: "shatter",
  Typewriter: "typewriter",
  Vaporwave: "vaporwave",
  Sunken: "sunken",
} as const;
/**
 * The stored name effect after the update
 */
export type V1AccountUpdateCosmeticsBodyNameEffect = OpenEnum<
  typeof V1AccountUpdateCosmeticsBodyNameEffect
>;

export type V1AccountUpdateCosmeticsBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  dollarSchema?: string | undefined;
  /**
   * The stored name effect after the update
   */
  nameEffect: V1AccountUpdateCosmeticsBodyNameEffect;
  /**
   * The stored theme color after the update, null when unset
   */
  themeColor: string | null;
};

/** @internal */
export const V1AccountUpdateCosmeticsBodyNameEffect$inboundSchema: z.ZodType<
  V1AccountUpdateCosmeticsBodyNameEffect,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(V1AccountUpdateCosmeticsBodyNameEffect);

/** @internal */
export const V1AccountUpdateCosmeticsBody$inboundSchema: z.ZodType<
  V1AccountUpdateCosmeticsBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  $schema: z.string().optional(),
  nameEffect: V1AccountUpdateCosmeticsBodyNameEffect$inboundSchema,
  themeColor: z.nullable(z.string()),
}).transform((v) => {
  return remap$(v, {
    "$schema": "dollarSchema",
  });
});

export function v1AccountUpdateCosmeticsBodyFromJSON(
  jsonString: string,
): SafeParseResult<V1AccountUpdateCosmeticsBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1AccountUpdateCosmeticsBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1AccountUpdateCosmeticsBody' from JSON`,
  );
}
