/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import {
    AccountLeaderboardHistory,
    AccountLeaderboardHistory$inboundSchema,
    AccountLeaderboardHistory$Outbound,
    AccountLeaderboardHistory$outboundSchema,
} from "./accountleaderboardhistory.js";
import * as z from "zod";

export type V1AccountLeaderboardHistoryResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    dollarSchema?: string | undefined;
    histories: Array<AccountLeaderboardHistory> | null;
};

/** @internal */
export const V1AccountLeaderboardHistoryResponseBody$inboundSchema: z.ZodType<
    V1AccountLeaderboardHistoryResponseBody,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        $schema: z.string().optional(),
        histories: z.nullable(z.array(AccountLeaderboardHistory$inboundSchema)),
    })
    .transform((v) => {
        return remap$(v, {
            $schema: "dollarSchema",
        });
    });

/** @internal */
export type V1AccountLeaderboardHistoryResponseBody$Outbound = {
    $schema?: string | undefined;
    histories: Array<AccountLeaderboardHistory$Outbound> | null;
};

/** @internal */
export const V1AccountLeaderboardHistoryResponseBody$outboundSchema: z.ZodType<
    V1AccountLeaderboardHistoryResponseBody$Outbound,
    z.ZodTypeDef,
    V1AccountLeaderboardHistoryResponseBody
> = z
    .object({
        dollarSchema: z.string().optional(),
        histories: z.nullable(z.array(AccountLeaderboardHistory$outboundSchema)),
    })
    .transform((v) => {
        return remap$(v, {
            dollarSchema: "$schema",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1AccountLeaderboardHistoryResponseBody$ {
    /** @deprecated use `V1AccountLeaderboardHistoryResponseBody$inboundSchema` instead. */
    export const inboundSchema = V1AccountLeaderboardHistoryResponseBody$inboundSchema;
    /** @deprecated use `V1AccountLeaderboardHistoryResponseBody$outboundSchema` instead. */
    export const outboundSchema = V1AccountLeaderboardHistoryResponseBody$outboundSchema;
    /** @deprecated use `V1AccountLeaderboardHistoryResponseBody$Outbound` instead. */
    export type Outbound = V1AccountLeaderboardHistoryResponseBody$Outbound;
}
