/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  V1AccountBadgeCountStats,
  V1AccountBadgeCountStats$inboundSchema,
  V1AccountBadgeCountStats$Outbound,
  V1AccountBadgeCountStats$outboundSchema,
} from "./v1accountbadgecountstats.js";
import {
  V1AccountBadgeXpStats,
  V1AccountBadgeXpStats$inboundSchema,
  V1AccountBadgeXpStats$Outbound,
  V1AccountBadgeXpStats$outboundSchema,
} from "./v1accountbadgexpstats.js";

export type V1AccountBadgeStats = {
  /**
   * A URL to the JSON Schema for this object.
   */
  dollarSchema?: string | undefined;
  count: V1AccountBadgeCountStats;
  levels: { [k: string]: number };
  scarcities: { [k: string]: number };
  /**
   * The total number of badges
   */
  totalBadges: number;
  xp: V1AccountBadgeXpStats;
};

/** @internal */
export const V1AccountBadgeStats$inboundSchema: z.ZodType<
  V1AccountBadgeStats,
  z.ZodTypeDef,
  unknown
> = z.object({
  $schema: z.string().optional(),
  count: V1AccountBadgeCountStats$inboundSchema,
  levels: z.record(z.number().int()),
  scarcities: z.record(z.number().int()),
  totalBadges: z.number().int(),
  xp: V1AccountBadgeXpStats$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "$schema": "dollarSchema",
  });
});

/** @internal */
export type V1AccountBadgeStats$Outbound = {
  $schema?: string | undefined;
  count: V1AccountBadgeCountStats$Outbound;
  levels: { [k: string]: number };
  scarcities: { [k: string]: number };
  totalBadges: number;
  xp: V1AccountBadgeXpStats$Outbound;
};

/** @internal */
export const V1AccountBadgeStats$outboundSchema: z.ZodType<
  V1AccountBadgeStats$Outbound,
  z.ZodTypeDef,
  V1AccountBadgeStats
> = z.object({
  dollarSchema: z.string().optional(),
  count: V1AccountBadgeCountStats$outboundSchema,
  levels: z.record(z.number().int()),
  scarcities: z.record(z.number().int()),
  totalBadges: z.number().int(),
  xp: V1AccountBadgeXpStats$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    dollarSchema: "$schema",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1AccountBadgeStats$ {
  /** @deprecated use `V1AccountBadgeStats$inboundSchema` instead. */
  export const inboundSchema = V1AccountBadgeStats$inboundSchema;
  /** @deprecated use `V1AccountBadgeStats$outboundSchema` instead. */
  export const outboundSchema = V1AccountBadgeStats$outboundSchema;
  /** @deprecated use `V1AccountBadgeStats$Outbound` instead. */
  export type Outbound = V1AccountBadgeStats$Outbound;
}

export function v1AccountBadgeStatsToJSON(
  v1AccountBadgeStats: V1AccountBadgeStats,
): string {
  return JSON.stringify(
    V1AccountBadgeStats$outboundSchema.parse(v1AccountBadgeStats),
  );
}

export function v1AccountBadgeStatsFromJSON(
  jsonString: string,
): SafeParseResult<V1AccountBadgeStats, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1AccountBadgeStats$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1AccountBadgeStats' from JSON`,
  );
}
