/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1AdminUserCounts = {
  /**
   * In the last 24 hours
   */
  day: number;
  /**
   * In the last 30 days
   */
  month: number;
  /**
   * In the last 7 days
   */
  week: number;
};

/** @internal */
export const V1AdminUserCounts$inboundSchema: z.ZodMiniType<
  V1AdminUserCounts,
  unknown
> = z.object({
  day: z.int(),
  month: z.int(),
  week: z.int(),
});

export function v1AdminUserCountsFromJSON(
  jsonString: string,
): SafeParseResult<V1AdminUserCounts, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1AdminUserCounts$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1AdminUserCounts' from JSON`,
  );
}
