/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type V1AdminCmsPreviewTokenRequestBody = {
  documentUid: string;
  versionUid: string;
};

/** @internal */
export type V1AdminCmsPreviewTokenRequestBody$Outbound = {
  document_uid: string;
  version_uid: string;
};

/** @internal */
export const V1AdminCmsPreviewTokenRequestBody$outboundSchema: z.ZodType<
  V1AdminCmsPreviewTokenRequestBody$Outbound,
  z.ZodTypeDef,
  V1AdminCmsPreviewTokenRequestBody
> = z.object({
  documentUid: z.string(),
  versionUid: z.string(),
}).transform((v) => {
  return remap$(v, {
    documentUid: "document_uid",
    versionUid: "version_uid",
  });
});

export function v1AdminCmsPreviewTokenRequestBodyToJSON(
  v1AdminCmsPreviewTokenRequestBody: V1AdminCmsPreviewTokenRequestBody,
): string {
  return JSON.stringify(
    V1AdminCmsPreviewTokenRequestBody$outboundSchema.parse(
      v1AdminCmsPreviewTokenRequestBody,
    ),
  );
}
