/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1AdminDonationsCreateCurrencyResponseBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  dollarSchema?: string | undefined;
  id: number;
};

/** @internal */
export const V1AdminDonationsCreateCurrencyResponseBody$inboundSchema:
  z.ZodType<V1AdminDonationsCreateCurrencyResponseBody, z.ZodTypeDef, unknown> =
    z.object({
      $schema: z.string().optional(),
      id: z.number().int(),
    }).transform((v) => {
      return remap$(v, {
        "$schema": "dollarSchema",
      });
    });

export function v1AdminDonationsCreateCurrencyResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  V1AdminDonationsCreateCurrencyResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V1AdminDonationsCreateCurrencyResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V1AdminDonationsCreateCurrencyResponseBody' from JSON`,
  );
}
