/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  IDSearch,
  IDSearch$Outbound,
  IDSearch$outboundSchema,
} from "./idsearch.js";
import {
  VanitySearch,
  VanitySearch$Outbound,
  VanitySearch$outboundSchema,
} from "./vanitysearch.js";

export type V1AdminRestrictAccountRequestBody = {
  id?: IDSearch | undefined;
  /**
   * Staff-facing reason for the restriction. Required when restricted is true, ignored when it is false.
   */
  reason?: string | undefined;
  /**
   * true hides the account site-wide and locks it out of login, false lifts both
   */
  restricted: boolean;
  vanity?: VanitySearch | undefined;
};

/** @internal */
export type V1AdminRestrictAccountRequestBody$Outbound = {
  id?: IDSearch$Outbound | undefined;
  reason?: string | undefined;
  restricted: boolean;
  vanity?: VanitySearch$Outbound | undefined;
};

/** @internal */
export const V1AdminRestrictAccountRequestBody$outboundSchema: z.ZodMiniType<
  V1AdminRestrictAccountRequestBody$Outbound,
  V1AdminRestrictAccountRequestBody
> = z.object({
  id: z.optional(IDSearch$outboundSchema),
  reason: z.optional(z.string()),
  restricted: z.boolean(),
  vanity: z.optional(VanitySearch$outboundSchema),
});

export function v1AdminRestrictAccountRequestBodyToJSON(
  v1AdminRestrictAccountRequestBody: V1AdminRestrictAccountRequestBody,
): string {
  return JSON.stringify(
    V1AdminRestrictAccountRequestBody$outboundSchema.parse(
      v1AdminRestrictAccountRequestBody,
    ),
  );
}
