/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { AdminCmsItem, AdminCmsItem$inboundSchema } from "./admincmsitem.js";

export type V1AdminCmsListResponseBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  dollarSchema?: string | undefined;
  items: Array<AdminCmsItem> | null;
};

/** @internal */
export const V1AdminCmsListResponseBody$inboundSchema: z.ZodType<
  V1AdminCmsListResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  $schema: z.string().optional(),
  items: z.nullable(z.array(AdminCmsItem$inboundSchema)),
}).transform((v) => {
  return remap$(v, {
    "$schema": "dollarSchema",
  });
});

export function v1AdminCmsListResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<V1AdminCmsListResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1AdminCmsListResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1AdminCmsListResponseBody' from JSON`,
  );
}
