/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type V1AdminFindSteamApiKeyRequestBody = {
  /**
   * The plaintext Steam Web API key to look up. Surrounding whitespace is ignored.
   */
  key: string;
};

/** @internal */
export type V1AdminFindSteamApiKeyRequestBody$Outbound = {
  key: string;
};

/** @internal */
export const V1AdminFindSteamApiKeyRequestBody$outboundSchema: z.ZodMiniType<
  V1AdminFindSteamApiKeyRequestBody$Outbound,
  V1AdminFindSteamApiKeyRequestBody
> = z.object({
  key: z.string(),
});

export function v1AdminFindSteamApiKeyRequestBodyToJSON(
  v1AdminFindSteamApiKeyRequestBody: V1AdminFindSteamApiKeyRequestBody,
): string {
  return JSON.stringify(
    V1AdminFindSteamApiKeyRequestBody$outboundSchema.parse(
      v1AdminFindSteamApiKeyRequestBody,
    ),
  );
}
