/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  CmsVersionItem,
  CmsVersionItem$inboundSchema,
} from "./cmsversionitem.js";

export type V1AdminCmsVersionsResponseBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  dollarSchema?: string | undefined;
  versions: Array<CmsVersionItem> | null;
};

/** @internal */
export const V1AdminCmsVersionsResponseBody$inboundSchema: z.ZodType<
  V1AdminCmsVersionsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  $schema: z.string().optional(),
  versions: z.nullable(z.array(CmsVersionItem$inboundSchema)),
}).transform((v) => {
  return remap$(v, {
    "$schema": "dollarSchema",
  });
});

export function v1AdminCmsVersionsResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<V1AdminCmsVersionsResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1AdminCmsVersionsResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1AdminCmsVersionsResponseBody' from JSON`,
  );
}
