/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1AdminTestSteamApiKeyResponseBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  dollarSchema?: string | undefined;
  /**
   * Human-readable result. Never contains the key.
   */
  message: string;
  /**
   * Number of Web API methods the key can call, across all interfaces
   */
  methods: number;
  /**
   * True when Steam answered HTTP 200
   */
  ok: boolean;
  /**
   * HTTP status from Steam, or 0 on a network error
   */
  status: number;
};

/** @internal */
export const V1AdminTestSteamApiKeyResponseBody$inboundSchema: z.ZodType<
  V1AdminTestSteamApiKeyResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  $schema: z.string().optional(),
  message: z.string(),
  methods: z.number().int(),
  ok: z.boolean(),
  status: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "$schema": "dollarSchema",
  });
});

export function v1AdminTestSteamApiKeyResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<V1AdminTestSteamApiKeyResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V1AdminTestSteamApiKeyResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1AdminTestSteamApiKeyResponseBody' from JSON`,
  );
}
