/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { Range, Range$Outbound, Range$outboundSchema } from "./range.js";

export type V1AppFilters = {
  /**
   * Filter by app type (e.g., 'game', 'dlc')
   */
  appType?: string | null | undefined;
  /**
   * Exclude event apps
   */
  excludeEvents?: boolean | null | undefined;
  /**
   * Exclude sale/promotional apps
   */
  excludeSales?: boolean | null | undefined;
  /**
   * If true, only apps where the account has crafted at least one badge; if false, only apps where it has crafted none
   */
  hasBadge?: boolean | null | undefined;
  playtime?: Range | undefined;
};

/** @internal */
export type V1AppFilters$Outbound = {
  appType?: string | null | undefined;
  excludeEvents?: boolean | null | undefined;
  excludeSales?: boolean | null | undefined;
  hasBadge?: boolean | null | undefined;
  playtime?: Range$Outbound | undefined;
};

/** @internal */
export const V1AppFilters$outboundSchema: z.ZodMiniType<
  V1AppFilters$Outbound,
  V1AppFilters
> = z.object({
  appType: z.optional(z.nullable(z.string())),
  excludeEvents: z.optional(z.nullable(z.boolean())),
  excludeSales: z.optional(z.nullable(z.boolean())),
  hasBadge: z.optional(z.nullable(z.boolean())),
  playtime: z.optional(Range$outboundSchema),
});

export function v1AppFiltersToJSON(v1AppFilters: V1AppFilters): string {
  return JSON.stringify(V1AppFilters$outboundSchema.parse(v1AppFilters));
}
