/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  AccountBadgeInfo,
  AccountBadgeInfo$inboundSchema,
} from "./accountbadgeinfo.js";

export type V1AppBadge = {
  accountInfo?: AccountBadgeInfo | null | undefined;
  appId: number;
  appImage: string;
  appName: string;
  badgeId: string;
  badgeImage: string;
  /**
   * The level this badge starts at
   */
  baseLevel: number;
  /**
   * The XP the badge gives per level
   */
  baseXp: number;
  /**
   * Total trading cards Steam defines for this app (per side; foil and normal share the same count)
   */
  cardCount: number;
  firstCompletion: Date | null;
  highestLevel: number;
  isEvent: boolean;
  isFoil: boolean;
  /**
   * Whether the cards needed for this badge are non-marketable on Steam (cannot be bought/sold)
   */
  isNmc: boolean;
  isSale: boolean;
  lastCompletion: Date | null;
  name: string;
  /**
   * Whether at least one card for this badge is not currently listed on the market
   */
  noListing: boolean;
  /**
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  price: number;
  scarcity: number;
  steamId: number;
  trackedHolders: number;
};

/** @internal */
export const V1AppBadge$inboundSchema: z.ZodMiniType<V1AppBadge, unknown> = z
  .object({
    accountInfo: z.optional(z.nullable(AccountBadgeInfo$inboundSchema)),
    appId: z.int(),
    appImage: z.string(),
    appName: z.string(),
    badgeId: z.string(),
    badgeImage: z.string(),
    baseLevel: z.int(),
    baseXp: z.int(),
    cardCount: z.int(),
    firstCompletion: z.nullable(
      z.pipe(z.iso.datetime({ offset: true }), z.transform(v => new Date(v))),
    ),
    highestLevel: z.int(),
    isEvent: z.boolean(),
    isFoil: z.boolean(),
    isNmc: z.boolean(),
    isSale: z.boolean(),
    lastCompletion: z.nullable(
      z.pipe(z.iso.datetime({ offset: true }), z.transform(v => new Date(v))),
    ),
    name: z.string(),
    noListing: z.boolean(),
    price: z.int(),
    scarcity: z.int(),
    steamId: z.int(),
    trackedHolders: z.int(),
  });

export function v1AppBadgeFromJSON(
  jsonString: string,
): SafeParseResult<V1AppBadge, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1AppBadge$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1AppBadge' from JSON`,
  );
}
