/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1BadgeSuggestSearchBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  dollarSchema?: string | undefined;
  /**
   * The filter to apply to the search
   */
  filter: string;
};

/** @internal */
export const V1BadgeSuggestSearchBody$inboundSchema: z.ZodType<
  V1BadgeSuggestSearchBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  $schema: z.string().optional(),
  filter: z.string(),
}).transform((v) => {
  return remap$(v, {
    "$schema": "dollarSchema",
  });
});

/** @internal */
export type V1BadgeSuggestSearchBody$Outbound = {
  $schema?: string | undefined;
  filter: string;
};

/** @internal */
export const V1BadgeSuggestSearchBody$outboundSchema: z.ZodType<
  V1BadgeSuggestSearchBody$Outbound,
  z.ZodTypeDef,
  V1BadgeSuggestSearchBody
> = z.object({
  dollarSchema: z.string().optional(),
  filter: z.string(),
}).transform((v) => {
  return remap$(v, {
    dollarSchema: "$schema",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1BadgeSuggestSearchBody$ {
  /** @deprecated use `V1BadgeSuggestSearchBody$inboundSchema` instead. */
  export const inboundSchema = V1BadgeSuggestSearchBody$inboundSchema;
  /** @deprecated use `V1BadgeSuggestSearchBody$outboundSchema` instead. */
  export const outboundSchema = V1BadgeSuggestSearchBody$outboundSchema;
  /** @deprecated use `V1BadgeSuggestSearchBody$Outbound` instead. */
  export type Outbound = V1BadgeSuggestSearchBody$Outbound;
}

export function v1BadgeSuggestSearchBodyToJSON(
  v1BadgeSuggestSearchBody: V1BadgeSuggestSearchBody,
): string {
  return JSON.stringify(
    V1BadgeSuggestSearchBody$outboundSchema.parse(v1BadgeSuggestSearchBody),
  );
}

export function v1BadgeSuggestSearchBodyFromJSON(
  jsonString: string,
): SafeParseResult<V1BadgeSuggestSearchBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1BadgeSuggestSearchBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1BadgeSuggestSearchBody' from JSON`,
  );
}
