/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1BadgeSuggestSearchRequestBody = {
  /**
   * The query to suggest a search for
   */
  query: string;
};

/** @internal */
export const V1BadgeSuggestSearchRequestBody$inboundSchema: z.ZodType<
  V1BadgeSuggestSearchRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  query: z.string(),
});

/** @internal */
export type V1BadgeSuggestSearchRequestBody$Outbound = {
  query: string;
};

/** @internal */
export const V1BadgeSuggestSearchRequestBody$outboundSchema: z.ZodType<
  V1BadgeSuggestSearchRequestBody$Outbound,
  z.ZodTypeDef,
  V1BadgeSuggestSearchRequestBody
> = z.object({
  query: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1BadgeSuggestSearchRequestBody$ {
  /** @deprecated use `V1BadgeSuggestSearchRequestBody$inboundSchema` instead. */
  export const inboundSchema = V1BadgeSuggestSearchRequestBody$inboundSchema;
  /** @deprecated use `V1BadgeSuggestSearchRequestBody$outboundSchema` instead. */
  export const outboundSchema = V1BadgeSuggestSearchRequestBody$outboundSchema;
  /** @deprecated use `V1BadgeSuggestSearchRequestBody$Outbound` instead. */
  export type Outbound = V1BadgeSuggestSearchRequestBody$Outbound;
}

export function v1BadgeSuggestSearchRequestBodyToJSON(
  v1BadgeSuggestSearchRequestBody: V1BadgeSuggestSearchRequestBody,
): string {
  return JSON.stringify(
    V1BadgeSuggestSearchRequestBody$outboundSchema.parse(
      v1BadgeSuggestSearchRequestBody,
    ),
  );
}

export function v1BadgeSuggestSearchRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<V1BadgeSuggestSearchRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1BadgeSuggestSearchRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1BadgeSuggestSearchRequestBody' from JSON`,
  );
}
