/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1BadgeBookmarkResponseBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  dollarSchema?: string | undefined;
};

/** @internal */
export const V1BadgeBookmarkResponseBody$inboundSchema: z.ZodType<
  V1BadgeBookmarkResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  $schema: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "$schema": "dollarSchema",
  });
});

/** @internal */
export type V1BadgeBookmarkResponseBody$Outbound = {
  $schema?: string | undefined;
};

/** @internal */
export const V1BadgeBookmarkResponseBody$outboundSchema: z.ZodType<
  V1BadgeBookmarkResponseBody$Outbound,
  z.ZodTypeDef,
  V1BadgeBookmarkResponseBody
> = z.object({
  dollarSchema: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    dollarSchema: "$schema",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1BadgeBookmarkResponseBody$ {
  /** @deprecated use `V1BadgeBookmarkResponseBody$inboundSchema` instead. */
  export const inboundSchema = V1BadgeBookmarkResponseBody$inboundSchema;
  /** @deprecated use `V1BadgeBookmarkResponseBody$outboundSchema` instead. */
  export const outboundSchema = V1BadgeBookmarkResponseBody$outboundSchema;
  /** @deprecated use `V1BadgeBookmarkResponseBody$Outbound` instead. */
  export type Outbound = V1BadgeBookmarkResponseBody$Outbound;
}

export function v1BadgeBookmarkResponseBodyToJSON(
  v1BadgeBookmarkResponseBody: V1BadgeBookmarkResponseBody,
): string {
  return JSON.stringify(
    V1BadgeBookmarkResponseBody$outboundSchema.parse(
      v1BadgeBookmarkResponseBody,
    ),
  );
}

export function v1BadgeBookmarkResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<V1BadgeBookmarkResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1BadgeBookmarkResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1BadgeBookmarkResponseBody' from JSON`,
  );
}
