/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type V1BadgeSuggestTagsRequestBody = {
  /**
   * The ID of the badge to suggest tags for
   */
  badgeId: string;
};

/** @internal */
export type V1BadgeSuggestTagsRequestBody$Outbound = {
  badgeId: string;
};

/** @internal */
export const V1BadgeSuggestTagsRequestBody$outboundSchema: z.ZodType<
  V1BadgeSuggestTagsRequestBody$Outbound,
  z.ZodTypeDef,
  V1BadgeSuggestTagsRequestBody
> = z.object({
  badgeId: z.string(),
});

export function v1BadgeSuggestTagsRequestBodyToJSON(
  v1BadgeSuggestTagsRequestBody: V1BadgeSuggestTagsRequestBody,
): string {
  return JSON.stringify(
    V1BadgeSuggestTagsRequestBody$outboundSchema.parse(
      v1BadgeSuggestTagsRequestBody,
    ),
  );
}
