/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type V1BadgeListBadgePricesRequestBody = {};

/** @internal */
export type V1BadgeListBadgePricesRequestBody$Outbound = {};

/** @internal */
export const V1BadgeListBadgePricesRequestBody$outboundSchema: z.ZodType<
  V1BadgeListBadgePricesRequestBody$Outbound,
  z.ZodTypeDef,
  V1BadgeListBadgePricesRequestBody
> = z.object({});

export function v1BadgeListBadgePricesRequestBodyToJSON(
  v1BadgeListBadgePricesRequestBody: V1BadgeListBadgePricesRequestBody,
): string {
  return JSON.stringify(
    V1BadgeListBadgePricesRequestBody$outboundSchema.parse(
      v1BadgeListBadgePricesRequestBody,
    ),
  );
}
