/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1DeleteSessionRequestBody = {
  /**
   * The session id to delete
   */
  sessionId: string;
};

/** @internal */
export const V1DeleteSessionRequestBody$inboundSchema: z.ZodType<
  V1DeleteSessionRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  sessionId: z.string(),
});

/** @internal */
export type V1DeleteSessionRequestBody$Outbound = {
  sessionId: string;
};

/** @internal */
export const V1DeleteSessionRequestBody$outboundSchema: z.ZodType<
  V1DeleteSessionRequestBody$Outbound,
  z.ZodTypeDef,
  V1DeleteSessionRequestBody
> = z.object({
  sessionId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1DeleteSessionRequestBody$ {
  /** @deprecated use `V1DeleteSessionRequestBody$inboundSchema` instead. */
  export const inboundSchema = V1DeleteSessionRequestBody$inboundSchema;
  /** @deprecated use `V1DeleteSessionRequestBody$outboundSchema` instead. */
  export const outboundSchema = V1DeleteSessionRequestBody$outboundSchema;
  /** @deprecated use `V1DeleteSessionRequestBody$Outbound` instead. */
  export type Outbound = V1DeleteSessionRequestBody$Outbound;
}

export function v1DeleteSessionRequestBodyToJSON(
  v1DeleteSessionRequestBody: V1DeleteSessionRequestBody,
): string {
  return JSON.stringify(
    V1DeleteSessionRequestBody$outboundSchema.parse(v1DeleteSessionRequestBody),
  );
}

export function v1DeleteSessionRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<V1DeleteSessionRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1DeleteSessionRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1DeleteSessionRequestBody' from JSON`,
  );
}
