/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Image,
  Image$inboundSchema,
  Image$Outbound,
  Image$outboundSchema,
} from "./image.js";

export type V1GetImagesResponseBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  dollarSchema?: string | undefined;
  /**
   * The images the account has
   */
  images: Array<Image> | null;
};

/** @internal */
export const V1GetImagesResponseBody$inboundSchema: z.ZodType<
  V1GetImagesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  $schema: z.string().optional(),
  images: z.nullable(z.array(Image$inboundSchema)),
}).transform((v) => {
  return remap$(v, {
    "$schema": "dollarSchema",
  });
});

/** @internal */
export type V1GetImagesResponseBody$Outbound = {
  $schema?: string | undefined;
  images: Array<Image$Outbound> | null;
};

/** @internal */
export const V1GetImagesResponseBody$outboundSchema: z.ZodType<
  V1GetImagesResponseBody$Outbound,
  z.ZodTypeDef,
  V1GetImagesResponseBody
> = z.object({
  dollarSchema: z.string().optional(),
  images: z.nullable(z.array(Image$outboundSchema)),
}).transform((v) => {
  return remap$(v, {
    dollarSchema: "$schema",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1GetImagesResponseBody$ {
  /** @deprecated use `V1GetImagesResponseBody$inboundSchema` instead. */
  export const inboundSchema = V1GetImagesResponseBody$inboundSchema;
  /** @deprecated use `V1GetImagesResponseBody$outboundSchema` instead. */
  export const outboundSchema = V1GetImagesResponseBody$outboundSchema;
  /** @deprecated use `V1GetImagesResponseBody$Outbound` instead. */
  export type Outbound = V1GetImagesResponseBody$Outbound;
}

export function v1GetImagesResponseBodyToJSON(
  v1GetImagesResponseBody: V1GetImagesResponseBody,
): string {
  return JSON.stringify(
    V1GetImagesResponseBody$outboundSchema.parse(v1GetImagesResponseBody),
  );
}

export function v1GetImagesResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<V1GetImagesResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1GetImagesResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1GetImagesResponseBody' from JSON`,
  );
}
