/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1LeaderboardGroupMetaResponseBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  dollarSchema?: string | undefined;
  description: string;
  title: string;
};

/** @internal */
export const V1LeaderboardGroupMetaResponseBody$inboundSchema: z.ZodType<
  V1LeaderboardGroupMetaResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  $schema: z.string().optional(),
  description: z.string(),
  title: z.string(),
}).transform((v) => {
  return remap$(v, {
    "$schema": "dollarSchema",
  });
});

/** @internal */
export type V1LeaderboardGroupMetaResponseBody$Outbound = {
  $schema?: string | undefined;
  description: string;
  title: string;
};

/** @internal */
export const V1LeaderboardGroupMetaResponseBody$outboundSchema: z.ZodType<
  V1LeaderboardGroupMetaResponseBody$Outbound,
  z.ZodTypeDef,
  V1LeaderboardGroupMetaResponseBody
> = z.object({
  dollarSchema: z.string().optional(),
  description: z.string(),
  title: z.string(),
}).transform((v) => {
  return remap$(v, {
    dollarSchema: "$schema",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1LeaderboardGroupMetaResponseBody$ {
  /** @deprecated use `V1LeaderboardGroupMetaResponseBody$inboundSchema` instead. */
  export const inboundSchema = V1LeaderboardGroupMetaResponseBody$inboundSchema;
  /** @deprecated use `V1LeaderboardGroupMetaResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    V1LeaderboardGroupMetaResponseBody$outboundSchema;
  /** @deprecated use `V1LeaderboardGroupMetaResponseBody$Outbound` instead. */
  export type Outbound = V1LeaderboardGroupMetaResponseBody$Outbound;
}

export function v1LeaderboardGroupMetaResponseBodyToJSON(
  v1LeaderboardGroupMetaResponseBody: V1LeaderboardGroupMetaResponseBody,
): string {
  return JSON.stringify(
    V1LeaderboardGroupMetaResponseBody$outboundSchema.parse(
      v1LeaderboardGroupMetaResponseBody,
    ),
  );
}

export function v1LeaderboardGroupMetaResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<V1LeaderboardGroupMetaResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V1LeaderboardGroupMetaResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1LeaderboardGroupMetaResponseBody' from JSON`,
  );
}
