/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1LeaderboardGetAccountsMetaResponseBody = {
  /**
   * A URL to the JSON Schema for this object.
   */
  dollarSchema?: string | undefined;
  description: string;
  title: string;
};

/** @internal */
export const V1LeaderboardGetAccountsMetaResponseBody$inboundSchema: z.ZodType<
  V1LeaderboardGetAccountsMetaResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  $schema: z.string().optional(),
  description: z.string(),
  title: z.string(),
}).transform((v) => {
  return remap$(v, {
    "$schema": "dollarSchema",
  });
});

export function v1LeaderboardGetAccountsMetaResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  V1LeaderboardGetAccountsMetaResponseBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V1LeaderboardGetAccountsMetaResponseBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V1LeaderboardGetAccountsMetaResponseBody' from JSON`,
  );
}
