/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type V1LeaderboardBadgeInfo = {
  /**
   * The id of the app
   */
  appId: number;
  /**
   * The image of the app
   */
  appImage: string;
  /**
   * The name of the app
   */
  appName: string;
  /**
   * The image of the badge
   */
  image: string;
  /**
   * Whether the badge is foil or not
   */
  isFoil: boolean;
  /**
   * The level of the badge
   */
  level: number;
  /**
   * The name of the badge
   */
  name: string;
};

/** @internal */
export const V1LeaderboardBadgeInfo$inboundSchema: z.ZodType<
  V1LeaderboardBadgeInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  appId: z.number().int(),
  appImage: z.string(),
  appName: z.string(),
  image: z.string(),
  isFoil: z.boolean(),
  level: z.number().int(),
  name: z.string(),
});

/** @internal */
export type V1LeaderboardBadgeInfo$Outbound = {
  appId: number;
  appImage: string;
  appName: string;
  image: string;
  isFoil: boolean;
  level: number;
  name: string;
};

/** @internal */
export const V1LeaderboardBadgeInfo$outboundSchema: z.ZodType<
  V1LeaderboardBadgeInfo$Outbound,
  z.ZodTypeDef,
  V1LeaderboardBadgeInfo
> = z.object({
  appId: z.number().int(),
  appImage: z.string(),
  appName: z.string(),
  image: z.string(),
  isFoil: z.boolean(),
  level: z.number().int(),
  name: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1LeaderboardBadgeInfo$ {
  /** @deprecated use `V1LeaderboardBadgeInfo$inboundSchema` instead. */
  export const inboundSchema = V1LeaderboardBadgeInfo$inboundSchema;
  /** @deprecated use `V1LeaderboardBadgeInfo$outboundSchema` instead. */
  export const outboundSchema = V1LeaderboardBadgeInfo$outboundSchema;
  /** @deprecated use `V1LeaderboardBadgeInfo$Outbound` instead. */
  export type Outbound = V1LeaderboardBadgeInfo$Outbound;
}
