/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * xp buckets by level; apps buckets by the game-collector badge thresholds.
 */
export const V1LeaderboardGetBucketLeadersRequestBodyLeaderboard = {
  Xp: "xp",
  Apps: "apps",
} as const;
/**
 * xp buckets by level; apps buckets by the game-collector badge thresholds.
 */
export type V1LeaderboardGetBucketLeadersRequestBodyLeaderboard = OpenEnum<
  typeof V1LeaderboardGetBucketLeadersRequestBodyLeaderboard
>;

export type V1LeaderboardGetBucketLeadersRequestBody = {
  /**
   * xp only: levels per bucket (default 10). Ignored for apps.
   */
  bucketSize?: number | undefined;
  /**
   * xp buckets by level; apps buckets by the game-collector badge thresholds.
   */
  leaderboard: V1LeaderboardGetBucketLeadersRequestBodyLeaderboard;
};

/** @internal */
export const V1LeaderboardGetBucketLeadersRequestBodyLeaderboard$outboundSchema:
  z.ZodType<
    string,
    z.ZodTypeDef,
    V1LeaderboardGetBucketLeadersRequestBodyLeaderboard
  > = openEnums.outboundSchema(
    V1LeaderboardGetBucketLeadersRequestBodyLeaderboard,
  );

/** @internal */
export type V1LeaderboardGetBucketLeadersRequestBody$Outbound = {
  bucketSize?: number | undefined;
  leaderboard: string;
};

/** @internal */
export const V1LeaderboardGetBucketLeadersRequestBody$outboundSchema: z.ZodType<
  V1LeaderboardGetBucketLeadersRequestBody$Outbound,
  z.ZodTypeDef,
  V1LeaderboardGetBucketLeadersRequestBody
> = z.object({
  bucketSize: z.number().int().optional(),
  leaderboard:
    V1LeaderboardGetBucketLeadersRequestBodyLeaderboard$outboundSchema,
});

export function v1LeaderboardGetBucketLeadersRequestBodyToJSON(
  v1LeaderboardGetBucketLeadersRequestBody:
    V1LeaderboardGetBucketLeadersRequestBody,
): string {
  return JSON.stringify(
    V1LeaderboardGetBucketLeadersRequestBody$outboundSchema.parse(
      v1LeaderboardGetBucketLeadersRequestBody,
    ),
  );
}
