/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  V1UpdateImage,
  V1UpdateImage$inboundSchema,
  V1UpdateImage$Outbound,
  V1UpdateImage$outboundSchema,
} from "./v1updateimage.js";

export type V1UpdateImageRequestBody = {
  /**
   * The images to update
   */
  images: Array<V1UpdateImage> | null;
};

/** @internal */
export const V1UpdateImageRequestBody$inboundSchema: z.ZodType<
  V1UpdateImageRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  images: z.nullable(z.array(V1UpdateImage$inboundSchema)),
});

/** @internal */
export type V1UpdateImageRequestBody$Outbound = {
  images: Array<V1UpdateImage$Outbound> | null;
};

/** @internal */
export const V1UpdateImageRequestBody$outboundSchema: z.ZodType<
  V1UpdateImageRequestBody$Outbound,
  z.ZodTypeDef,
  V1UpdateImageRequestBody
> = z.object({
  images: z.nullable(z.array(V1UpdateImage$outboundSchema)),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1UpdateImageRequestBody$ {
  /** @deprecated use `V1UpdateImageRequestBody$inboundSchema` instead. */
  export const inboundSchema = V1UpdateImageRequestBody$inboundSchema;
  /** @deprecated use `V1UpdateImageRequestBody$outboundSchema` instead. */
  export const outboundSchema = V1UpdateImageRequestBody$outboundSchema;
  /** @deprecated use `V1UpdateImageRequestBody$Outbound` instead. */
  export type Outbound = V1UpdateImageRequestBody$Outbound;
}

export function v1UpdateImageRequestBodyToJSON(
  v1UpdateImageRequestBody: V1UpdateImageRequestBody,
): string {
  return JSON.stringify(
    V1UpdateImageRequestBody$outboundSchema.parse(v1UpdateImageRequestBody),
  );
}

export function v1UpdateImageRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<V1UpdateImageRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1UpdateImageRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1UpdateImageRequestBody' from JSON`,
  );
}
