/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The role the account should have between one of the 6 donation roles
 */
export const V1UpdateRoleRequestBodyRole = {
  Amber: "amber",
  Amethyst: "amethyst",
  Emerald: "emerald",
  Sapphire: "sapphire",
  Ruby: "ruby",
  Diamond: "diamond",
} as const;
/**
 * The role the account should have between one of the 6 donation roles
 */
export type V1UpdateRoleRequestBodyRole = ClosedEnum<
  typeof V1UpdateRoleRequestBodyRole
>;

export type V1UpdateRoleRequestBody = {
  /**
   * The role the account should have between one of the 6 donation roles
   */
  role?: V1UpdateRoleRequestBodyRole | undefined;
};

/** @internal */
export const V1UpdateRoleRequestBodyRole$inboundSchema: z.ZodNativeEnum<
  typeof V1UpdateRoleRequestBodyRole
> = z.nativeEnum(V1UpdateRoleRequestBodyRole);

/** @internal */
export const V1UpdateRoleRequestBodyRole$outboundSchema: z.ZodNativeEnum<
  typeof V1UpdateRoleRequestBodyRole
> = V1UpdateRoleRequestBodyRole$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1UpdateRoleRequestBodyRole$ {
  /** @deprecated use `V1UpdateRoleRequestBodyRole$inboundSchema` instead. */
  export const inboundSchema = V1UpdateRoleRequestBodyRole$inboundSchema;
  /** @deprecated use `V1UpdateRoleRequestBodyRole$outboundSchema` instead. */
  export const outboundSchema = V1UpdateRoleRequestBodyRole$outboundSchema;
}

/** @internal */
export const V1UpdateRoleRequestBody$inboundSchema: z.ZodType<
  V1UpdateRoleRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  role: V1UpdateRoleRequestBodyRole$inboundSchema.optional(),
});

/** @internal */
export type V1UpdateRoleRequestBody$Outbound = {
  role?: string | undefined;
};

/** @internal */
export const V1UpdateRoleRequestBody$outboundSchema: z.ZodType<
  V1UpdateRoleRequestBody$Outbound,
  z.ZodTypeDef,
  V1UpdateRoleRequestBody
> = z.object({
  role: V1UpdateRoleRequestBodyRole$outboundSchema.optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1UpdateRoleRequestBody$ {
  /** @deprecated use `V1UpdateRoleRequestBody$inboundSchema` instead. */
  export const inboundSchema = V1UpdateRoleRequestBody$inboundSchema;
  /** @deprecated use `V1UpdateRoleRequestBody$outboundSchema` instead. */
  export const outboundSchema = V1UpdateRoleRequestBody$outboundSchema;
  /** @deprecated use `V1UpdateRoleRequestBody$Outbound` instead. */
  export type Outbound = V1UpdateRoleRequestBody$Outbound;
}

export function v1UpdateRoleRequestBodyToJSON(
  v1UpdateRoleRequestBody: V1UpdateRoleRequestBody,
): string {
  return JSON.stringify(
    V1UpdateRoleRequestBody$outboundSchema.parse(v1UpdateRoleRequestBody),
  );
}

export function v1UpdateRoleRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<V1UpdateRoleRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1UpdateRoleRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1UpdateRoleRequestBody' from JSON`,
  );
}
